### ISSUE TITLE
StableDiffusion3Pipeline.from_single_file error：module 'torch' has no attribute 'float8_e4m3fn'

### ISSUE THREAD

**Issue by zhaoyun0071** [huggingface/diffusers#8537] opened 2024-06-13 15:46 UTC
### Describe the bug

error below：

site-packages\safetensors\torch.py", line 313, in load_file
    result[k] = f.get_tensor(k)
AttributeError: module 'torch' has no attribute 'float8_e4m3fn'

### Reproduction

import torch
from diffusers import StableDiffusion3Pipeline

```
pipe = StableDiffusion3Pipeline.from_single_file(
    r"sd3_medium_incl_clips_t5xxlfp8.safetensors",
    torch_dtype=torch.float16,
)
pipe.enable_model_cpu_offload()

image = pipe("a picture of a cat holding a sign that says hello world").images[0]
image.save('sd3-single-file-t5-fp8.png')

```

### System Info

diffusers 0.29.0

### Who can help?

@yiyixuxu @DN6 @sayakpaul

**Comment by tolgacangoz** [comment] 2024-06-13 16:03
It says "'torch' has no attribute 'something'". So, this probably means you need a newer version of `torch` having this 'something'. Could you just upgrade your `torch`?

**Comment by bghira** [comment] 2024-06-13 17:21
chances are your device doesn't support fp8. use the fp16 checkpoint

**Comment by tommyj8** [comment] 2024-06-16 08:53
Sharing the solution found on [huggingface](https://huggingface.co/stabilityai/stable-diffusion-3-medium/discussions/11#6669fd30d70d5346025bf6f5)

`pip install --upgrade torch torchvision torchaudio -r requirements.txt`

**Comment by asomoza** [comment] 2024-06-16 11:38
probably we need to add this somewhere in the documentation @stevhliu , to be able to use `float8_e4m3fn` you need torch 2.3

**Comment by stevhliu** [comment] 2024-06-17 16:18
Perhaps we can add a `[!TIP]` [here](https://huggingface.co/docs/diffusers/main/en/api/pipelines/stable_diffusion/stable_diffusion_3#loading-the-single-file-checkpoint-without-t5) with a suggestion to use torch 2.3?

**Comment by asomoza** [comment] 2024-06-18 19:25
Oh yeah, that makes a lot of sense to me.

**Comment by DN6** [comment] 2024-07-01 11:01
Updating to Torch 2.3 seems to be the solution here right? Closing this as completed.

**Closed by DN6** 2024-07-01 11:01 UTC
Labels: bug

**Comment by GlitchBanger** [comment] 2024-07-24 05:40
Didn't work for me. I upgraded torch and I still get that same error.

**Comment by DN6** [comment] 2024-07-25 14:16
@GlitchBanger Could you open a separate issue with a minimal code example I can use to reproduce the error. Could you also share the output of `diffusers-cli env` in your issue please.
