### ISSUE TITLE
Unable to use custom text_encoder in `StableDiffusionPipeline.from_single_file`

### ISSUE THREAD

**Issue by lss233** [huggingface/diffusers#4446] opened 2023-08-03 03:33 UTC
### Describe the bug

Hi, I was trying to use load a custom `text_encoder`  with a CIVITAI downloaded safetensors in `StableDiffusionPipeline`, but the following errors occurd. 

Is this a bug or am I missing something?

### Reproduction

```python
import torch
from diffusers import EulerDiscreteScheduler
from diffusers import StableDiffusionPipeline
from torch import autocast
from transformers import CLIPTextModel

clip = CLIPTextModel.from_pretrained("openai/clip-vit-large-patch14", num_hidden_layers=11, torch_dtype=torch.float16)

# This one is ok
# pipeline = StableDiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5", text_encoder = clip).to("cuda")

# But this is not ok
pipeline = StableDiffusionPipeline.from_single_file(
    "/path/to/stable-diffusion-webui/models/Stable-diffusion/cetusMix_v4.safetensors",
    text_encoder = clip
).to("cuda")

pipeline.scheduler = EulerDiscreteScheduler.from_config(pipeline.scheduler.config)
generator = torch.Generator(device="cuda").manual_seed(233)
with autocast("cuda"):
    images = pipeline(
        "1girl",
        width=512,
        height=512,
        num_images_per_prompt=1,
        generator=generator,
        num_inference_steps=20,
        guidance_scale=7.0).images
```

### Logs

```shell
In this conversion only the non-EMA weights are extracted. If you want to instead extract the EMA weights (usually better for inference), please make sure to add the `--extract_ema` flag.
Traceback (most recent call last):
  File "/tmp/pycharm_project_461/reproducable.py", line 10, in <module>
    pipeline = StableDiffusionPipeline.from_single_file(
  File "/usr/lib/python3.10/site-packages/diffusers/loaders.py", line 1924, in from_single_file
    pipe = download_from_original_stable_diffusion_ckpt(
  File "/usr/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py", line 1501, in download_from_original_stable_diffusion_ckpt
    text_model = convert_ldm_clip_checkpoint(
  File "/usr/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py", line 800, in convert_ldm_clip_checkpoint
    set_module_tensor_to_device(text_model, param_name, "cpu", value=param)
UnboundLocalError: local variable 'text_model' referenced before assignment
```

### System Info

- `diffusers` version: 0.19.3
- Platform: Linux-5.4.119-1-tlinux4-0010.3-x86_64-with-glibc2.28
- Python version: 3.10.10
- PyTorch version (GPU?): 2.0.1+cu118 (True)
- Huggingface_hub version: 0.15.1
- Transformers version: 4.25.1
- Accelerate version: 0.18.0
- xFormers version: 0.0.20
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: parallel

### Who can help?

@patrickvonplaten, @sayakpaul, @williamberman

**Comment by patrickvonplaten** [comment] 2023-08-03 19:38
@DN6 could you maybe give this a try?

**Comment by adi-bhatl-1998** [comment] 2023-08-09 04:02
HFValidationError: Repo id must use alphanumeric chars or '-', '_', '.', '--' and '..' are forbidden, '-' and '.' 
cannot start or end the name, max length is 96: '/path'.
not able to reproduce your error

**Comment by sayakpaul** [comment] 2023-08-17 03:15
Should be fixed with https://github.com/huggingface/diffusers/pull/4571.

**Closed by sayakpaul** 2023-08-17 03:15 UTC
Labels: bug

**Comment by babyta** [comment] 2023-12-14 07:15
Hello, I encountered a similar problem. I would like to ask if the clip is not included in the model when I load a separate model?What I use is cyberrealistic_v33，
StableDiffusionPipeline.from_single_file （
original_config_file = 
text_encoder = CLIPTextModel.from_pretrained(clip_path)
）
