### ISSUE TITLE
Switching to DPM++ SDE Karras sampling method

### ISSUE THREAD

**Issue by gameveloster** [huggingface/diffusers#2064] opened 2023-01-23 01:11 UTC
How can I change the scheduler in `StableDiffusionPipeline` to use what AUTOMATIC111's gui calls the "DPM++ SDE Karras" sampling method?

Also, whats the default sampling method being used by `StableDiffusionPipeline`?

**Comment by patrickvonplaten** [comment] 2023-01-23 08:53
This might be the only scheduler method we don't have yet - I assume you referring to: https://github.com/crowsonkb/k-diffusion/blob/41b4cb6df0506694a7776af31349acf082bf6091/k_diffusion/sampling.py#L543

Think this is already the second issue about it, would be extremely nice to add it then. Maybe someone from the community has time to do it ? :-) Will try to find some time otherwise.

Here a nice doc on how to change schedulers in general: https://huggingface.co/docs/diffusers/main/en/using-diffusers/schedulers

**Comment by A0158** [comment] 2023-01-23 08:54
You can use this to find alternative of DPM++ SDE Karras in `StableDiffusionPipeline` :
https://huggingface.co/docs/diffusers/v0.11.0/en/api/schedulers/multistep_dpm_solver#diffusers.DPMSolverMultistepScheduler

You can also try:
https://huggingface.co/docs/diffusers/api/schedulers/dpm_discrete

The default sampling method used by `StableDiffusionPipeline` is [PNDMScheduler](https://huggingface.co/docs/diffusers/v0.11.0/en/api/schedulers/pndm#diffusers.PNDMScheduler).

I hope this helps :)

**Comment by A0158** [comment] 2023-01-23 09:16
Hi @patrickvonplaten , 

I am interested to add it.

**Comment by patrickvonplaten** [comment] 2023-01-24 13:12
@A0158,

This would be great :-) Do you want to open a PR for it? 

It's quite useful to compare your implementation with https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_k_diffusion.py to make sure results are the same

**Comment by A0158** [comment] 2023-01-24 18:54
Yeah ! I will open a PR for it. 

Thanks for letting me know. I will compare the implementation to verify the results.

**Comment by jslegers** [comment] 2023-01-27 04:43
Has output for the different schedulers in `diffusers` been compared with output in the AUTOMATIC1111 gui?

When testing [Epic Diffusion](https://huggingface.co/johnslegers/epic-diffusion-v1.1), I was unable to reproduce the output of a basic `diffusers` script with that of any of the schedulers in the AUTOMATIC1111 gui; regardless of using the same seed, CFG scale & other parameters.

I initially suspected this may be related to how the AUTOMATIC1111 GUI overcomes the [77 token limit of CLIP](https://github.com/huggingface/diffusers/issues/2136), but after reading the description of how they achieve this I'm less convinced...

**Comment by patrickvonplaten** [comment] 2023-01-31 08:13
Hey @jslegers,

For the future, it would be great if you could open a new issue. I've answered here in more detail: https://huggingface.co/spaces/anzorq/finetuned_diffusion/discussions/64

**Comment by jslegers** [comment] 2023-01-31 08:40
> For the future, it would be great if you could open a new issue. 

Personally, I'm not a fan of raising issues for just asking a question. In my experience, as a senior software developer, this easily leads to issue-spam and makes it difficult to keep an overview of actual bugs & feature requests. Also, I felt this issue was related enough to not warrant raising a new issue.

But I'll try to keep your different preference in mind for the future whenever I have similar questions.

**Comment by patrickvonplaten** [comment] 2023-01-31 13:33
It's a bit easier to find issues according to the issue title later on, so we usually prefer to open new issues when the topic is slightly different.

**Comment by patrickvonplaten** [comment] 2023-03-23 12:58
Hey @nipunjindal,

This sounds great! Let me know if you need help

**Comment by nipunjindal** [comment] 2023-03-28 17:51
Hello @patrickvonplaten,

Happy to get some help here. I am unable to find text related to this scheduler, do you mind sharing the way to go about it?
Thanks! Should be able to complete it this week, once I get jump-started.

**Comment by patrickvonplaten** [comment] 2023-03-30 16:45
Hey @nipunjindal,

Would this feature request maybe help: https://github.com/huggingface/diffusers/issues/2905 

Essentially, it's not really a new scheduler, it just uses different sigmas. We could quite easily support this with a `use_karras_sigmas` flag I think :-)

**Comment by patrickvonplaten** [comment] 2023-03-30 16:45
Hey @nipunjindal,

Would this feature request maybe help: https://github.com/huggingface/diffusers/issues/2905 

Essentially, it's not really a new scheduler, it just uses different sigmas. We could quite easily support this with a `use_karras_sigmas` flag I think :-)

**Comment by nipunjindal** [comment] 2023-03-30 16:49
@patrickvonplaten,

Thanks definitely this is helpful, if that's the case, to me the kdiffusion code din't appear like that. But I can always test out with the kdiffusion pipeline.
Nonetheless, on this journey I went through the issue of Scheduler Design and it was super helpful for me to so much more accustomed to the system. Will report back tomorrow.

**Comment by LuChengTHU** [comment] 2023-05-05 13:50
I've added the "correct" version of the SDE-type DPM-Solver++: https://github.com/huggingface/diffusers/pull/3344

**Comment by sayakpaul** [comment] 2023-06-20 11:13
Closing this with https://github.com/huggingface/diffusers/pull/3344

**Closed by sayakpaul** 2023-06-20 11:13 UTC
Labels: New scheduler
