### ISSUE TITLE
Batch Processing for Multi ControlNet.

### ISSUE THREAD

**Issue by ahmadmustafaanis** [huggingface/diffusers#2704] opened 2023-03-16 07:22 UTC
### Describe the bug

I am trying to use Batch Processing for Multi ControlNet, but it does not work as intended.

### Reproduction

```
pipe = StableDiffusionControlNetPipeline.from_pretrained(
    "my_model", torch_dtype=torch.float16,
    controlnet=[
        controlnet_pose, 
        controlnet_hed
    ],
).to("cuda")

output = pipe(
        ["prompt 1", "prompt 2"],   # Batch Processing for 2 prompts
        [[pose_image_low, hed_image_low], [pose_image_cc, hed_image_cc]],  # 2 Images for each prompt
        generator = [torch.Generator(device="cuda").manual_seed(16605685601386031741), torch.Generator(device="cuda").manual_seed(16605685601386031741)],  # 2 generators for each prompt
        negative_prompt=["low quality, wrong face, distorted face, ugly, beard", "low quality, wrong face, distorted face, tikka, ugly, beard"],  # 2 neg prompts
        num_inference_steps=50,
    controlnet_conditioning_scale = [1, 1.2, 1, 0.7]  # This gives an error
controlnet_conditioning_scale = [[1, 1.2], [1, 0.7]] # this gives an error
controlnet_conditioning_scale = [1, 1.2] # this works fine but I want to use different conditioning scale for both prompts
).images
```

### System Info

Latest installation
```
pip install git+https://github.com/huggingface/diffusers
```
GPU: Tesla T4

**Comment by patrickvonplaten** [comment] 2023-03-16 15:33
Yes this looks like an error to me, thanks for the issue @ahmadmustafaanis . @williamberman could you have a look here?

**Comment by takuma104** [comment] 2023-03-17 13:59
At present, the `controlnet_conditioning_scale` parameter did not support batches. It did not allow List [before Multi-ControlNet support was added](https://github.com/huggingface/diffusers/blob/4ae54b37898cf2c97518038d5028645bdb816dca/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_controlnet.py#L661). The current version with Multi-ControlNet support still inherits this specification and does not support batches. If `controlnet_conditioning_scale = [1, 1.2]` is specified, it does not apply to batches, but rather corresponds to each ControlNet. `controlnet_conditioning_scale=1` is passed to `controlnet_pose`, and `controlnet_conditioning_scale=1.2` is passed to `controlnet_hed`.

It can be confusing to determine which parameter supports batches and which does not, as both Batch and Multi-ControlNet use List specification.

**Comment by takuma104** [comment] 2023-03-17 14:15
```py
        [[pose_image_low, hed_image_low], [pose_image_cc, hed_image_cc]],  # 2 Images for each prompt
```
This part is also not very straightforward, but In the current implementation, it is necessary to do it this way to achieve the intended behavior.
```py
        [[pose_image_low, pose_image_cc], [hed_image_low, hed_image_cc]],  # 2 Images for each prompt
```

**Comment by patrickvonplaten** [comment] 2023-03-21 12:44
@williamberman @sayakpaul could you check here?

**Comment by sayakpaul** [comment] 2023-03-22 02:14
> It can be confusing to determine which parameter supports batches and which does not, as both Batch and Multi-ControlNet use list specification. Is there any better solution to this problem?

I agree. I think we could just log information to the users when these cases arrive to keep the API design not too complicated. One reference for that would be how it's handled in the InstructPix2Pix pipeline:

https://github.com/huggingface/diffusers/blob/7fe88613fa15d230d59482889c440c7befa17c25/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_instruct_pix2pix.py#L730

**Comment by patrickvonplaten** [comment] 2023-03-23 12:45
Let's try to open a PR here to fix it maybe @sayakpaul or @williamberman ?

**Comment by sayakpaul** [comment] 2023-03-28 02:54
Closing this issue in favor of https://github.com/huggingface/diffusers/issues/2855

**Closed by sayakpaul** 2023-03-28 02:54 UTC
Labels: bug
