### ISSUE TITLE
Error when loading ControlNetModel

### ISSUE THREAD

**Issue by domef** [huggingface/diffusers#4389] opened 2023-07-31 12:57 UTC
### Describe the bug

When creating a `ControlNetModel` object an error is raised. If I run `pip install accelerate` as suggested in the logs it work fine.
My question is: why `accelerate` is not in the requirements of `diffusers` if it is necessary to load some models?

### Reproduction

```python
from diffusers import ControlNetModel

controlnet = ControlNetModel.from_pretrained("lllyasviel/sd-controlnet-depth")
```

### Logs

```shell
Cannot initialize model with low cpu memory usage because `accelerate` was not found in the environment. Defaulting to `low_cpu_mem_usage=False`. It is strongly recommended to install `accelerate` for faster and less memory-intense model loading. You can do so with: 
\```
pip install accelerate
\```
.
Downloading (…)lve/main/config.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 920/920 [00:00<00:00, 87.8kB/s]
Downloading (…)ch_model.safetensors: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 1.45G/1.45G [00:18<00:00, 78.2MB/s]
Traceback (most recent call last):
  File "/home/federico/Desktop/bug_diffusers/.venv/lib/python3.8/site-packages/diffusers/models/modeling_utils.py", line 109, in load_state_dict
    return safetensors.torch.load_file(checkpoint_file, device="cpu")
AttributeError: module 'safetensors' has no attribute 'torch'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/federico/Desktop/bug_diffusers/.venv/lib/python3.8/site-packages/diffusers/models/modeling_utils.py", line 113, in load_state_dict
    if f.read().startswith("version"):
  File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbc in position 0: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "program.py", line 15, in <module>
    controlnet = ControlNetModel.from_pretrained("lllyasviel/sd-controlnet-depth")
  File "/home/federico/Desktop/bug_diffusers/.venv/lib/python3.8/site-packages/diffusers/models/modeling_utils.py", line 697, in from_pretrained
    state_dict = load_state_dict(model_file, variant=variant)
  File "/home/federico/Desktop/bug_diffusers/.venv/lib/python3.8/site-packages/diffusers/models/modeling_utils.py", line 125, in load_state_dict
    raise OSError(
OSError: Unable to load weights from checkpoint file for '/home/federico/.cache/huggingface/hub/models--lllyasviel--sd-controlnet-depth/snapshots/35e42a3ea49845b3c76f202f145f257b9fb1b7d4/diffusion_pytorch_model.safetensors' at '/home/federico/.cache/huggingface/hub/models--lllyasviel--sd-controlnet-depth/snapshots/35e42a3ea49845b3c76f202f145f257b9fb1b7d4/diffusion_pytorch_model.safetensors'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.
```

### System Info

- `diffusers` version: 0.19.3
- Platform: Linux-5.19.0-50-generic-x86_64-with-glibc2.35
- Python version: 3.8.17
- PyTorch version (GPU?): 1.13.1+cu117 (True)
- Huggingface_hub version: 0.16.4
- Transformers version: not installed
- Accelerate version: not installed
- xFormers version: not installed
- Using GPU in script?: no
- Using distributed or parallel set-up in script?: no

**Comment by patrickvonplaten** [comment] 2023-07-31 19:24
Duplicate of https://github.com/huggingface/diffusers/issues/4390

**Comment by sayakpaul** [comment] 2023-08-02 09:16
Closing this then.

**Closed by sayakpaul** 2023-08-02 09:16 UTC
Labels: bug
