### ISSUE TITLE
load multiple LORAs, and the load time increases linearly

### ISSUE THREAD

**Issue by javey-q** [huggingface/diffusers#9297] opened 2024-08-28 07:52 UTC
### Describe the bug

I try to load multiple LORAs into the SDXL pipe，and  the load time increases linearly.
But when i uninstall the peft according to the previous issue，the load time becomes stable.

### Reproduction

```python
from time import perf_counter
from diffusers import StableDiffusionXLPipeline, AutoencoderKL

vae = AutoencoderKL.from_pretrained(
    "madebyollin/sdxl-vae-fp16-fix", 
    torch_dtype=torch.float16,
    cache_dir='/data1/workspace/javeyqiu/models/huggingface/hub'
).to("cuda")
pipe = StableDiffusionXLPipeline.from_pretrained("/data1/workspace/javeyqiu/models/stable-diffusion-xl-base-1.0", 
                                         torch_dtype=torch.float16, 
                                         vae=vae,
                                         use_safetensors=True, 
                                         variant="fp16").to("cuda")
LOCAL_LORA_MODELS_PATH ="my-loras"
for i in range(10):
    lora_name = f"lora{i}"
    start = perf_counter()
    pipe.load_lora_weights(os.path.join(LOCAL_LORA_MODELS_PATH, lora_name),
        weight_name="lora.safetensors",
        local_files_only=True,
        adapter_name=lora_name)
    endtime = perf_counter()-start
    print("Load a lora took time: ", endtime, "s")
```

### Logs

```shell
Load a lora took time:  1.2157482262700796 s
Load a lora took time:  1.5895664589479566 s
Load a lora took time:  1.7863030601292849 s
Load a lora took time:  1.9525490580126643 s
Load a lora took time:  2.279414465650916 s
Load a lora took time:  2.3282409673556685 s
Load a lora took time:  2.4987880922853947 s
Load a lora took time:  2.705487427301705 s
Load a lora took time:  2.8978137467056513 s
Load a lora took time:  3.35094244312495 s
```

### System Info

- `diffusers` version: 0.27.2
- Platform: Linux-5.4.119-19.0009.28-x86_64-with-glibc2.28
- Python version: 3.10.14
- PyTorch version (GPU?): 2.2.2+cu121 (True)
- Huggingface_hub version: 0.23.4
- Transformers version: 4.44.0
- Accelerate version: 0.32.1
- xFormers version: 0.0.25.post1
- Using GPU in script?:  T4
- Using distributed or parallel set-up in script?:  distributed 

### Who can help?

@sayakpaul

**Comment by sayakpaul** [comment] 2024-08-28 07:55
Cc: @BenjaminBossan

**Comment by BenjaminBossan** [comment] 2024-08-28 10:53
Might be related to #8953. As mentioned, there is draft PR and there is also a contributor who wants to work on this, but they are unfortunately a bit slow.

I'll check this slowdown further to see if there is anything else tough.

Here is a reproducer with just public models:

```python
from time import perf_counter
import torch
from diffusers import StableDiffusionXLPipeline, AutoencoderKL

pipe = StableDiffusionXLPipeline.from_pretrained(
    "stabilityai/stable-diffusion-xl-base-1.0",
    torch_dtype=torch.float16,
    use_safetensors=True,
    variant="fp16",
).to("cuda")

LOCAL_LORA_MODELS_PATH ="my-loras"
for i in range(30):
    lora_name = "ostris/crayon_style_lora_sdxl"
    start = perf_counter()
    pipe.load_lora_weights(
        lora_name,
        weight_name="crayons_v1_sdxl.safetensors",
    )
    endtime = perf_counter()-start
    print(f"Lora {i:>2} took time: {endtime:.4f} s")
```

For me, this gives:

```
Lora  0 took time: 0.6020 s
Lora  1 took time: 0.8556 s
Lora  2 took time: 0.8307 s
Lora  3 took time: 0.9452 s
Lora  4 took time: 0.9991 s
Lora  5 took time: 1.1643 s
Lora  6 took time: 1.2778 s
Lora  7 took time: 1.2829 s
Lora  8 took time: 1.3212 s
Lora  9 took time: 1.5993 s
Lora 10 took time: 1.5593 s
Lora 11 took time: 1.5947 s
Lora 12 took time: 1.8830 s
Lora 13 took time: 1.6981 s
Lora 14 took time: 1.7802 s
Lora 15 took time: 2.0501 s
Lora 16 took time: 2.0273 s
Lora 17 took time: 2.0692 s
Lora 18 took time: 2.2604 s
Lora 19 took time: 2.3684 s
Lora 20 took time: 2.3044 s
Lora 21 took time: 2.2855 s
Lora 22 took time: 2.4007 s
Lora 23 took time: 2.4700 s
Lora 24 took time: 2.4927 s
Lora 25 took time: 2.6461 s
Lora 26 took time: 2.8541 s
Lora 27 took time: 2.7876 s
Lora 28 took time: 3.2160 s
Lora 29 took time: 3.0980 s
```

So for me, the slowdown is not quite as severe but still noticeable.

**Comment by BenjaminBossan** [comment] 2024-08-28 14:54
Okay, I made some progress. A big source of the slowdown is that for each potential module, we perform a check in PEFT if the name matches with the `target_modules`. Usually, `target_modules` are very short sequences in PEFT, e.g. `{"q_proj", "v_proj"}`. However, when I checked the `target_modules` we get for the example I posted above, it contains 582 items!

When I boiled down the `target_modules` to the bare minimum, i.e. the unique suffixes (in this case `{'0', 'to_k', 'to_v', 'proj_out', 'proj_in', 'to_q'}`), I could drastically reduce the load time:

```
Lora  0 took time: 511.6 ms
Lora  1 took time: 583.5 ms
Lora  2 took time: 425.2 ms
Lora  3 took time: 436.6 ms
Lora  4 took time: 464.3 ms
Lora  5 took time: 463.1 ms
Lora  6 took time: 665.9 ms
Lora  7 took time: 511.9 ms
Lora  8 took time: 527.4 ms
Lora  9 took time: 541.4 ms
Lora 10 took time: 576.4 ms
Lora 11 took time: 807.9 ms
Lora 12 took time: 574.6 ms
Lora 13 took time: 589.1 ms
Lora 14 took time: 602.7 ms
Lora 15 took time: 612.2 ms
Lora 16 took time: 613.7 ms
Lora 17 took time: 625.5 ms
Lora 18 took time: 631.8 ms
Lora 19 took time: 930.7 ms
Lora 20 took time: 674.8 ms
Lora 21 took time: 681.7 ms
Lora 22 took time: 719.8 ms
Lora 23 took time: 821.4 ms
Lora 24 took time: 740.5 ms
Lora 25 took time: 770.0 ms
Lora 26 took time: 783.6 ms
Lora 27 took time: 1093.6 ms
Lora 28 took time: 804.7 ms
Lora 29 took time: 798.1 ms
```

It's still increasing (for other reasons that are hard to avoid) but slow enough that it shouldn't matter mostly (especially once empty weight loading I mentioned above is implemented).

The `target_modules` are determined by diffusers here:

https://github.com/huggingface/diffusers/blob/cbc2ec8f44449cbc888256499d71bb6d7196aaa2/src/diffusers/utils/peft_utils.py#L181

This explains why they are so large: Since the loaded LoRA adapter does not have a `adapter_config.json` as defined in PEFT, diffusers cannot know the minimal set of `target_modules`, so instead diffusers derives this from the actually observed LoRA weights, so it effectively lists each targeted layer separately, explaining why we have 582 entries.

The reduction to the unique suffixes may work in this case but it may not always work. This is because theoretically, whoever trained the LoRA adapter may have target 99 `proj_in` layers but omitted a single one, in which case we cannot simple say: take all layers whose name ends with `proj_in`.

## Solution proposal 1

We could add some complex rules in diffusers to check for redundancies in `target_modules`, making sure that issues like above don't occur. But this sounds kinda error prone and complicated.

## Solution proposal 2

We can try to decrease the algorithmic complexity on the PEFT side. here is the line:

```
        target_module_found = any(key.endswith(f".{target_key}") for target_key in config.target_modules)
```

https://github.com/huggingface/peft/blob/850eeb5c3a5cf692f5612c7c733b13fde184e05d/src/peft/tuners/tuners_utils.py#L738

Ad hoc, I don't have an idea how this can be optimized.

**Comment by sayakpaul** [comment] 2024-08-29 03:48
Thanks so much @BenjaminBossan!

> When I boiled down the target_modules to the bare minimum, i.e. the unique suffixes (in this case {'0', 'to_k', 'to_v', 'proj_out', 'proj_in', 'to_q'}), I could drastically reduce the load time:

Could we not implement this? Perhaps, we could maintain a map of the unique suffixes (classified by libraries) and then lift off the algorithmic complexity a bit?

**Comment by BenjaminBossan** [comment] 2024-08-29 10:37
> Could we not implement this? Perhaps, we could maintain a map of the unique suffixes (classified by libraries) and then lift off the algorithmic complexity a bit?

Not sure if it's easily possible. In this specific case, this is probably enough:

```python
target_modules = {name.rsplit(".", 1)[-1] for name in peft_config.target_modules}
```

But this could easily fail if some modules are incorrectly matched. If we have such false positives, we would create a LoRA module on those layer for no reason. Unfortunately, that would not result in an error, instead these unnecessary LoRA layers would be initialized as identity transform. Therefore, the end result would not change and it would appear that everything is in order. But those layers would still require extra memory and compute, which really want to avoid.

Another issue with my snippet would be if the real target modules are something like `foo.bar`. In that case, I cannot split on the last `.`, since the suffix needs to contain a `.`.

All of this can be solved of course using some search algorithm that can determine the minimum set of suffixes that matches all of the desired keys but none of the undesired ones. This code would probably be quite complex and error prone. Honestly, this sounds like a good task for the highest tier of leet code ;-)

**Comment by sayakpaul** [comment] 2024-08-29 10:58
Okay thanks for explaining! 

Do you maybe wanna give Solution 1 a try and see how much complicacy we're introducing?

**Comment by BenjaminBossan** [comment] 2024-08-29 14:43
Okay, I* could come up with something that appears to work.

*I wrote something but it was algorithmically super inefficient, so ChatGPT improved it for me.

The function is:

```python
def find_unique_suffixes(list1, list2):
    def generate_suffixes(s):
        parts = s.split('.')
        return ['.'.join(parts[i:]) for i in range(len(parts))]

    # Create a reverse lookup for list2 to quickly check suffix matches
    list2_suffixes = {suffix for item in list2 for suffix in generate_suffixes(item)}

    # Find all potential suffixes from list1
    list1_suffix_map = {item: generate_suffixes(item) for item in list1}

    # Initialize a set for required suffixes
    required_suffixes = set()

    # Go through list1 items, shortest suffixes first
    for item, suffixes in list1_suffix_map.items():
        for suffix in sorted(suffixes, key=lambda x: (x.count("."), len(x), x)):
            # If the suffix is already in required_suffixes or matches list2, skip it
            if suffix in required_suffixes or suffix in list2_suffixes:
                continue
            # Check if adding this suffix covers the item
            if not any(item.endswith(req_suffix) for req_suffix in required_suffixes):
                required_suffixes.add(suffix)
                break

    return required_suffixes
```

IIUC, the final result may not be the actual optimal outcome, as it is a form of greedy search, but in practice should be good enough.

In diffusers, I added the following lines before `inject_adapter_in_model` is called inside of [`_process_lora`](https://github.com/huggingface/diffusers/blob/4f495b06dcbbc3437a598a20718fe74c29308756/src/diffusers/loaders/unet.py#L339):

```python
            reduced_target_modules = find_unique_suffixes(
                lora_config.target_modules, [n for n, _ in self.named_modules() if n not in lora_config.target_modules]
            )
            assert reduced_target_modules
            lora_config.target_modules = reduced_target_modules
```

I guess we could also add this on the PEFT side instead. I think it's only really a problem with diffusers but who knows.

I verified that `target_modules` was reduced to just 6 items and that the load times are now much more moderate:

```
Lora  0 took time: 642.8 ms
Lora  1 took time: 453.6 ms
Lora  2 took time: 476.8 ms
Lora  3 took time: 519.4 ms
Lora  4 took time: 625.6 ms
Lora  5 took time: 508.1 ms
Lora  6 took time: 537.5 ms
Lora  7 took time: 527.9 ms
Lora  8 took time: 609.2 ms
Lora  9 took time: 596.0 ms
Lora 10 took time: 812.3 ms
Lora 11 took time: 655.2 ms
Lora 12 took time: 623.9 ms
Lora 13 took time: 638.0 ms
Lora 14 took time: 647.9 ms
Lora 15 took time: 825.5 ms
Lora 16 took time: 904.8 ms
Lora 17 took time: 742.6 ms
Lora 18 took time: 714.6 ms
Lora 19 took time: 757.7 ms
Lora 20 took time: 755.9 ms
Lora 21 took time: 878.9 ms
Lora 22 took time: 814.1 ms
Lora 23 took time: 821.8 ms
Lora 24 took time: 1107.3 ms
Lora 25 took time: 924.9 ms
Lora 26 took time: 943.0 ms
Lora 27 took time: 917.7 ms
Lora 28 took time: 980.0 ms
Lora 29 took time: 958.2 ms
```

This is not production ready, as it would need to be inserted in more places than what I did, it needs unit test and probably some sanity checks. Maybe it should only be called when `target_modules` exceeds a certain length to avoid applying this if there is no point.

**Comment by sayakpaul** [comment] 2024-08-29 19:19
Thanks much!

> In diffusers, I added the following lines before inject_adapter_in_model is called inside of [_process_lora](https://github.com/huggingface/diffusers/blob/4f495b06dcbbc3437a598a20718fe74c29308756/src/diffusers/loaders/unet.py#L339):

Hmm, just for the sake of completeness, we would need to add a similar guard to text encoders inside `transformers`, too no?

> This is not production ready, as it would need to be inserted in more places than what I did

That is right. Here
https://github.com/huggingface/diffusers/blob/4f495b06dcbbc3437a598a20718fe74c29308756/src/diffusers/loaders/lora_pipeline.py#L1222

and similar instances of where `inject_adapter_in_model()` is used there. 

> it needs unit test and probably some sanity checks. Maybe it should only be called when target_modules exceeds a certain length to avoid applying this if there is no point.

I think we could design rigorous unit tests on the expected `target_modules` for the small models that we use for our LoRA tests. Sanity checks -- this I am not very sure at this point. 

WDYT?

**Comment by BenjaminBossan** [comment] 2024-08-30 08:14
After some thinking, I will include this in PEFT. There could be rare situations where this is useful there, so I'll take care of this.

**Comment by BenjaminBossan** [comment] 2024-08-30 12:04
I created a PR to add the optimization to PEFT: https://github.com/huggingface/peft/pull/2045

**Comment by sayakpaul** [comment] 2024-09-03 08:13
@javey-q please check https://github.com/huggingface/peft/pull/2045 if that solves your problem. I am going to close this issue for now.

**Closed by sayakpaul** 2024-09-03 08:13 UTC
Labels: bug
