### ISSUE TITLE
How to let diffusers use  local code for pipelineinstead of download it online everytime  We use it?

### ISSUE THREAD

**Issue by Kevin-shihello-world** [huggingface/diffusers#6819] opened 2024-02-02 02:53 UTC
I tried to use the instaflowpipeline from example/community to.run my test  However, even after i git cloned the repository to my environment it still  Keep trying to  Download the latest object of the instaflow pipeline code  Unfortunately in my area is hard for the environment to download it directly from rawgithub. I tried to change the downloaded code to let it just use these code already in my environment  But find it hard to change the path to url.
 I would be appreciated if someone could find an proper answer . Thank you for your time and happy lunar new year!

**Comment by DN6** [comment] 2024-02-05 12:12
@Kevin-shihello-world Can you share a code example for how you are trying to load the pipeline?

**Comment by DN6** [comment] 2024-02-06 16:44
@cool-bigdogs-tshirt I don't think it's related to this issue. But if you are experiencing an issue with single file would you mind opening a new issue with a reproducible code snippet please?

**Comment by Sanster** [comment] 2024-04-12 03:41
> a recent refactor broke some projects by removing `config_files` from `from_single_file`: [fee93c8#diff-e4c59f1e6ef65de50f554faa85ba27174c9fa11641082cb2e15f88b100e8b9afL150](https://github.com/huggingface/diffusers/commit/fee93c81eb7c5e9fe1618f858f1e369567170edc#diff-e4c59f1e6ef65de50f554faa85ba27174c9fa11641082cb2e15f88b100e8b9afL150)
> 
> last working commit is here:
> 
> https://github.com/huggingface/diffusers/blob/5308cce994ffb1b2c169d62a8f49d445442dff47/src/diffusers/loaders/single_file.py#L150

I also encountered this problem. The current `from_single_file` API has removed the `config_files` parameter. You can use the `original_config_file` parameter to pass the path of the yaml configuration file corresponding to different models.

**Comment by sayakpaul** [comment] 2024-11-28 05:44
Closing due to lack of activities. Feel free to reopen.

**Closed by sayakpaul** 2024-11-28 05:44 UTC
