### ISSUE TITLE
[Community Pipelines] lpw_stable_diffusion.py incompatible with Diffusers v0.10.0

### ISSUE THREAD

**Issue by WASasquatch** [huggingface/diffusers#1500] opened 2022-12-01 02:40 UTC
### Describe the bug

When trying to load Stable Diffusion v2.0 with Diffusers v0.10.0 you are greeted with error below

```
ValueError: Pipeline <class 'diffusers_modules.git.lpw_stable_diffusion.StableDiffusionLongPromptWeightingPipeline'> expected {'tokenizer', 'text_encoder', 'unet', 'vae', 'safety_checker', 'feature_extractor', 'scheduler'}, but only {'vae', 'tokenizer', 'safety_checker', 'text_encoder', 'scheduler', 'unet'} were passed.
```

### Reproduction

1. Load custom pipeline `lpw_stable_diffusion` in diffusers v0.10.0

### Logs

```shell
D:\ProgramData\Anaconda3\lib\site-packages\diffusers\pipeline_utils.py in from_pretrained(cls, pretrained_model_name_or_path, **kwargs)
    672         elif len(missing_modules) > 0:
    673             passed_modules = set(list(init_kwargs.keys()) + list(passed_class_obj.keys())) - optional_kwargs
--> 674             raise ValueError(
    675                 f"Pipeline {pipeline_class} expected {expected_modules}, but only {passed_modules} were passed."
    676             )

ValueError: Pipeline <class 'diffusers_modules.git.lpw_stable_diffusion.StableDiffusionLongPromptWeightingPipeline'> expected {'tokenizer', 'text_encoder', 'unet', 'vae', 'safety_checker', 'feature_extractor', 'scheduler'}, but only {'vae', 'tokenizer', 'safety_checker', 'text_encoder', 'scheduler', 'unet'} were passed.
```

### System Info
- `diffusers` version: 0.10.0.dev0
- Platform: Windows-10-10.0.22621-SP0
- Python version: 3.9.13
- PyTorch version (GPU?): 1.12.1 (True)
- Huggingface_hub version: 0.11.0
- Transformers version: 4.24.0
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

**Comment by WASasquatch** [comment] 2022-12-01 04:47
I seem to have inadvertently fixed whatever the issue was with adding a couple fixed for Stable Diffusion v2.0

**Comment by WASasquatch** [comment] 2022-12-02 18:08
Actually, I take that back. The issue still persists. It just only gives the error when using Stable Diffusion v2.0 model it seems for some reason.

**Comment by adhikjoshi** [comment] 2022-12-04 07:22
Have the same issue, it turns out lpw_stable_diffusion is not compatible with latest version of diffusers nor with new version of transformers. Its breaking changes.

https://github.com/huggingface/diffusers/issues/1536

**Comment by WASasquatch** [comment] 2022-12-04 20:03
> Have the same issue, it turns out lpw_stable_diffusion is not compatible with latest version of diffusers nor with new version of transformers. Its breaking changes.
> 
> #1536

I feel this just adds to the whole thing that Community Pipelines is just simply a bad approach. They're adopted into diffusers, but are not maintained by diffusers. They're all quickly become broken pipes at the rate of development and require community action, if anyone bothers. 

However, on v0.10.0 I am able to use LPW pipe fine, with redshift diffusion, and v1.5 of SD. When I load v2.0 of SD, that's when I encounter an error.

**Comment by Skquark** [comment] 2022-12-04 20:21
A workaround fix for that is to add feature_extractor=None to your pipeline calls.  Also if you're using enable_attention_slicing, the lpw pipe is not updated with the fix for slice_size when using SD2.  I have my own custom lpw pipeline with that updated on huggingface which you can load with custom_pipeline="AlanB/lpw_stable_diffusion_mod" if you wanna borrow it until the official correction is make.
I'm still having issues with 3 of the schedulers generating those ugly mosaic images using lpw with v2.0 and I don't know the cause/fix for that problem yet... Just patiently waiting while the dust settles.

**Comment by patrickvonplaten** [comment] 2022-12-05 19:05
Gently pinging @SkyTNT here

**Comment by anton-l** [comment] 2022-12-12 15:07
Fixed by @SkyTNT in https://github.com/huggingface/diffusers/pull/1570

**Closed by anton-l** 2022-12-12 15:07 UTC
Labels: bug
