### ISSUE TITLE
convert_lora_safetensor_to_diffusers

### ISSUE THREAD

**Issue by NicholasKao1029** [huggingface/diffusers#2829] opened 2023-03-26 00:00 UTC
this script `https://github.com/huggingface/diffusers/blob/main/scripts/convert_lora_safetensor_to_diffusers.py` integrates the lora into the Pipeline and then outputs said Pipeline.

Is there a method to turn the `.safetensors` Lora to a `.bin` file to be loaded in dynamically similar to the snippet below
```
from diffusers import StableDiffusionPipeline
import torch

model_path = "sayakpaul/sd-model-finetuned-lora-t4"
pipe = StableDiffusionPipeline.from_pretrained("CompVis/stable-diffusion-v1-4", torch_dtype=torch.float16)
pipe.unet.load_attn_procs(model_path)
pipe.to("cuda")

prompt = "A pokemon with blue eyes."
image = pipe(prompt, num_inference_steps=30, guidance_scale=7.5, cross_attention_kwargs={"scale": 0.5}).images[0]
image.save("pokemon.png")
```

As seen here https://huggingface.co/docs/diffusers/training/lora 

My complaint is there is a lot of redundancy in the model if you want different loras to be used.

**Comment by sayakpaul** [comment] 2023-03-27 09:28
Cc: @patrickvonplaten @Narsil

**Comment by Narsil** [comment] 2023-03-27 11:27
The conversion of the LoRA should only be a key remapping right ? 

`load_attn_procs` already supports loading LoRA from safetensors file. I think the problem is that SD-safetensors != diffusers-safetensors. (The name of the tensors are different). Am I correct ?

**Comment by NicholasKao1029** [comment] 2023-03-27 23:35
Sorry I misunderstood @Narsil, you are right it is only a key remapping, 
However  my point still holds true as the output is ultimately a full model

**Comment by sayakpaul** [comment] 2023-03-28 06:04
IIUC we output the full model for generality across different pipelines and also to keep the output artifacts to be as self-contained as possible. If you have some ideas on how we can improve this bit, feel free to open a PR :) 

@patrickvonplaten Cc.

**Comment by fungiboletus** [comment] 2023-03-28 08:00
I was expecting the script to generate a lora and not a whole model. Is it possible to convert the safetensors lora to diffusers lora? Or should we wait for the next release that should support safetensors lora without conversion ?

**Comment by YulienPohl** [comment] 2023-03-28 15:42
> Edit: I found a conversion script there: https://github.com/haofanwang/Lora-for-Diffusers/blob/18adfa4da0afec46679eb567d5a3690fd6a4ce9c/format_convert.py#L154-L161

For me this script does not work, it returns a 48 MB bin from a 144 MB safetensor.
And when I use it, it only creates images with colored spots.

**Comment by NicholasKao1029** [comment] 2023-03-28 17:58
@patrickvonplaten this would be fantastic!

**Comment by NicholasKao1029** [comment] 2023-03-31 19:07
Updated PR: https://github.com/huggingface/diffusers/pull/2918

**Comment by sayakpaul** [comment] 2023-04-04 08:57
Regarding the `safetensors` LoRA thing, does it make sense?
https://github.com/huggingface/diffusers/issues/2866#issuecomment-1495599465

**Comment by NicholasKao1029** [comment] 2023-04-16 01:29
> Regarding the `safetensors` LoRA thing, does it make sense? [#2866 (comment)](https://github.com/huggingface/diffusers/issues/2866#issuecomment-1495599465)

Sorry for the late reply @sayakpaul.

If I understand the linked comment, that would be for `.bin` -> `safetensors` for loras. Is there a corresponding `safetensors` -> `.bin` planned here or perhaps I misunderstood

**Comment by sayakpaul** [comment] 2023-04-16 07:55
The workflow still remains the same. 

You first download the `.safetensors` file. Let's call the downloaded model path - `model_filepath`. 

Then you load it:

```py
import safetensors

pt_state_dict = safetensors.torch.load_file(model_filepath, device="cpu")
```

Referencing:

https://github.com/huggingface/diffusers/blob/b811964a7b7f3c4cd50dc25a58789a0fed351e09/src/diffusers/loaders.py#L188

Then we can do:

```python
torch.save(pt_state_dict, "pt_state_dict.bin")
```

And then it should be just:

```py
pipeline.unet.load_attn_procs("pt_state_dict.bin")
```

A couple of other tings that might be worth noting regarding loading `safetensors` and operating with it seamlessly. 

Note it's also possible to directly load a `.safetensors` file with `load_attn_procs()` from the Hugging Face Hub. Let's the HF Hub repo id is: `username/repo_containing_lora_files_in_safetensors`. 

We can then do:

```py
pipeline.unet.load_attn_procs("username/repo_containing_lora_files_in_safetensors", use_safetensors=True)
```

Explicitly specifying `use_safetensors` is not necessary because we always prioritize on `safetensors` by default. 

For more details, I welcome you to check out:

https://github.com/huggingface/diffusers/blob/b811964a7b7f3c4cd50dc25a58789a0fed351e09/src/diffusers/loaders.py#L158-L193

I hope this helps.

**Comment by NicholasKao1029** [comment] 2023-04-17 00:10
Thanks @sayakpaul for the detailed explanation, I'm running into this issue https://github.com/huggingface/diffusers/issues/3064 I'll follow that one for updates

**Comment by sayakpaul** [comment] 2023-04-17 02:32
Closing this issue then. Feel free to re-open.

**Closed by sayakpaul** 2023-04-17 02:32 UTC

**Comment by ShoufaChen** [comment] 2023-12-26 01:39
Thanks for @sayakpaul's answer. I found that for recent safetensors I should load by:

```
from safetensors.torch import load_file
model = load_file(xxx)
```

because directly use `import safetensors safetensors.torch.load_file(xxx)`
would raise `AttributeError: module 'safetensors' has no attribute 'torch'`.

Just post here in case it might be helpful.
