### ISSUE TITLE
IndexError: index 21 is out of bounds for dimension 0 with size 21

### ISSUE THREAD

**Issue by TheHonestBob** [huggingface/diffusers#5749] opened 2023-11-10 09:04 UTC
### Describe the bug

I use Flask to deploy services，use StableDiffusionXLControlNetPipeline.from_single_file，When there are multiple concurrent requests, an error will be reported, and a single request will not report an error

### Reproduction

The following is the main code
image_device = 'cuda:1'
control_net = ControlNetModel.from_pretrained("pretrain_weight/controlnet-canny-sdxl-1.0",
                                              torch_dtype=torch.float16)
vae = AutoencoderKL.from_pretrained("pretrain_weight/sdxl-vae", torch_dtype=torch.float16)
pipe = StableDiffusionXLControlNetPipeline.from_single_file(
    r'sd_weight/lbedobaseXL_v11.safetensors',
    controlnet=control_net,
    vae=vae,
    torch_dtype=torch.float16,
    cache_dir='sd_weight',
    local_files_only=False
).to(image_device)

### Logs

```shell
Traceback (most recent call last):
  File "/data/user/chenbo/.conda/envs/llm_env/lib/python3.9/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/data/user/chenbo/.conda/envs/llm_env/lib/python3.9/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/data/user/chenbo/.conda/envs/llm_env/lib/python3.9/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/data/user/chenbo/.conda/envs/llm_env/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/data/user/chenbo/.conda/envs/llm_env/lib/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/data/user/chenbo/ImageGen/server_product.py", line 125, in img2img
    images = pipe(**sd_parameter).images
  File "/data/user/chenbo/.conda/envs/llm_env/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/data/user/chenbo/.conda/envs/llm_env/lib/python3.9/site-packages/diffusers/pipelines/controlnet/pipeline_controlnet_sd_xl.py", line 1221, in __call__
    latents = self.scheduler.step(noise_pred, t, latents, **extra_step_kwargs, return_dict=False)[0]
  File "/data/user/chenbo/.conda/envs/llm_env/lib/python3.9/site-packages/diffusers/schedulers/scheduling_euler_discrete.py", line 427, in step
    dt = self.sigmas[self.step_index + 1] - sigma_hat
IndexError: index 21 is out of bounds for dimension 0 with size 21
```

### System Info

diffusers                     0.23.0.dev0
ubuntu20
python 3.10

**Comment by yiyixuxu** [comment] 2023-11-10 09:20
hi @TheHonestBob 

I don't think you code matches with the stack trace :) .... would you be able to provide or recreate the code example that will cause this same error?

Thanks!

YiYi

**Comment by TheHonestBob** [comment] 2023-11-10 09:22
> hi @TheHonestBob
> 
> I don't think you code matches with the stack trace :) .... would you be able to provide or recreate the code example that will cause this same error?
> 
> Thanks!
> 
> YiYi

here is all code
# -*- coding: utf-8 -*-
"""
@author:cb
@contact:chenbo@quarkintl.com
@time:2023/11/3 13:40
@filename:server_product.py
@software:PyCharm 
@description:生产环境下的图生图，图生文flask服务
"""

import os
import base64
import json
import torch
import io
import cv2
import time
from deep_model import DeepDanbooruModel
import numpy as np
from PIL import Image
from flask import Flask, request
from flask_cors import CORS
from transformers import Blip2Processor, Blip2ForConditionalGeneration
from diffusers.utils import load_image
from diffusers import ControlNetModel, StableDiffusionXLControlNetPipeline, AutoencoderKL
app = Flask(__name__)
CORS(app, resources=r'/*', supports_credentials=True)


ACCESSkEY = 'QGvRXhpZgAATU0AKgAA'


def get_img(img_base64):
    img = base64.b64decode(img_base64)
    img = Image.open(io.BytesIO(img))
    return img


def process_img(img: Image):
    pass


@app.route("/img-to-text", methods=['GET', 'POST'])
def img2text():
    access_key = request.headers.get('accessKey', '')
    messages = request.get_json()
    # 校验access_key
    if access_key != ACCESSkEY:
        result_json = {"code": '000001', "msg": "refuse error, {}".format(access_key)}
        return result_json
    # 校验图像
    img = messages.get('img', '')
    img = img.split(',')
    if len(img) != 2:
        result_json = {"code": '000002', "msg": "miss image header"}
        return result_json
    img_header, img = img
    max_length = messages.get('textLength', 77)
    try:
        img = get_img(img)
    except OSError:
        result_json = {"code": '000003', "msg": "miss image data"}
        return result_json
    inputs = tokenizer(images=img, return_tensors="pt").to(text_device, torch.float16)
    generated_ids = model.generate(**inputs, max_length=max_length)
    generated_text = tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0].strip()
    deep_text = ','.join(deep_booru.predict(img).keys())
    result_json = {
        "code": '000000',
        "msg": "success",
        "data": {
            "text": generated_text + deep_text
        }
    }
    return json.dumps(result_json, ensure_ascii=False)


@app.route("/img-to-img", methods=['GET', 'POST'])
def img2img():
    access_key = request.headers.get('accessKey', '')
    # 校验access_key
    if access_key != ACCESSkEY:
        result_json = {"code": '000001', "msg": "refuse error, {}".format(access_key)}
        return result_json
    # 校验图像
    messages = request.get_json()
    print('接受到请求{}'.format(messages.get('num', -1)).center(50, '='))
    start_time = time.time()
    img = messages.get('img', '')
    img = img.split(',')
    if len(img) != 2:
        result_json = {"code": '000002', "msg": "miss image header"}
        return result_json
    prompt = messages.get('prompt', '')
    negative_prompt = messages.get('negativePrompt', '')
    height = messages.get('height', 960)
    width = messages.get('width', 544)
    num_inference_steps = messages.get('steps', 20)
    num_images_per_prompt = messages.get('imgNumber', 3)
    guidance_scale = messages.get('guidance_scale', 8.0)
    controlnet_conditioning_scale = messages.get('controlnet_conditioning_scale', 0.6)
    sd_parameter = {
        'prompt': prompt,
        'negative_prompt': negative_prompt,
        'height': height,
        'width': width,
        'num_inference_steps': num_inference_steps,
        'num_images_per_prompt': num_images_per_prompt,
        'guidance_scale': guidance_scale,
        'controlnet_conditioning_scale': controlnet_conditioning_scale
    }
    img_header, img = img
    try:
        img = get_img(img)
    except OSError:
        result_json = {"code": '000003', "msg": "miss image data"}
        return result_json

    user_img = np.asarray(load_image(img))
    image = cv2.Canny(user_img, 100, 200)
    image = image[:, :, None]
    image = np.concatenate([image, image, image], axis=2)
    image = Image.fromarray(image)
    sd_parameter.update({'image': image})
    images = pipe(**sd_parameter).images
    img_list = []
    for each_img in images:
        buff = io.BytesIO()
        each_img.save(buff, format='JPEG')
        img_base = base64.b64encode(buff.getvalue())
        img_list.append(img_header + ',' + str(img_base, encoding='utf-8'))
    result_json = {
        "success": True,
        "errCode": "string",
        "errMsg": "string",
        "totalRows": 0,
        "pageNo": 0,
        "pageSize": 0,
        "totalPages": 0,
        "data": {
            "imgList": img_list
        }
    }
    print('图生图耗时：{}, 生成{}张！'.format(time.time() - start_time, num_images_per_prompt).center(50, '='))
    return json.dumps(result_json, ensure_ascii=False)


if __name__ == '__main__':
    # torch.multiprocessing.set_start_method('spawn')
    # 1. img2text模型
    text_device = 'cuda:1'
    weights = r'pretrain_weight/blip2-opt-2.7b'
    tokenizer = Blip2Processor.from_pretrained(weights)
    model = Blip2ForConditionalGeneration.from_pretrained(weights, load_in_8bit=True, torch_dtype=torch.float16,
                                                          device_map=text_device)
    deep_booru = DeepDanbooruModel('model-resnet_custom_v3.pt', text_device, 0.7)
    # 2. img2img模型
    image_device = 'cuda:1'
    control_net = ControlNetModel.from_pretrained("pretrain_weight/controlnet-canny-sdxl-1.0",
                                                  torch_dtype=torch.float16)
    vae = AutoencoderKL.from_pretrained("pretrain_weight/sdxl-vae", torch_dtype=torch.float16)
    pipe = StableDiffusionXLControlNetPipeline.from_single_file(
        r'sd_weight/lbedobaseXL_v11.safetensors',
        controlnet=control_net,
        vae=vae,
        torch_dtype=torch.float16,
        cache_dir='sd_weight',
        local_files_only=False
    ).to(image_device)
    app.run('0.0.0.0', port=49000, debug=False, threaded=False, processes=1)

**Comment by TheHonestBob** [comment] 2023-11-10 09:27
> hi @TheHonestBob
> 
> I don't think you code matches with the stack trace :) .... would you be able to provide or recreate the code example that will cause this same error?
> 
> Thanks!
> 
> YiYi

`# -*- coding: utf-8 -*-
"""
@author:cb
@contact:chenbo@quarkintl.com
@time:2023/11/10 17:24
@filename:a.py
@software:PyCharm 
@description:
"""
import os
import base64
import json
import torch
import io
import cv2
import time
from deep_model import DeepDanbooruModel
import numpy as np
from PIL import Image
from flask import Flask, request
from flask_cors import CORS
from transformers import Blip2Processor, Blip2ForConditionalGeneration
from diffusers.utils import load_image
from diffusers import ControlNetModel, StableDiffusionXLControlNetPipeline, AutoencoderKL
app = Flask(__name__)
CORS(app, resources=r'/*', supports_credentials=True)


ACCESSkEY = 'QGvRXhpZgAATU0AKgAA'


def get_img(img_base64):
    img = base64.b64decode(img_base64)
    img = Image.open(io.BytesIO(img))
    return img


@app.route("/img-to-img", methods=['GET', 'POST'])
def img2img():
    access_key = request.headers.get('accessKey', '')
    # 校验access_key
    if access_key != ACCESSkEY:
        result_json = {"code": '000001', "msg": "refuse error, {}".format(access_key)}
        return result_json
    # 校验图像
    messages = request.get_json()
    print('接受到请求{}'.format(messages.get('num', -1)).center(50, '='))
    start_time = time.time()
    img = messages.get('img', '')
    img = img.split(',')
    if len(img) != 2:
        result_json = {"code": '000002', "msg": "miss image header"}
        return result_json
    prompt = messages.get('prompt', '')
    negative_prompt = messages.get('negativePrompt', '')
    height = messages.get('height', 960)
    width = messages.get('width', 544)
    num_inference_steps = messages.get('steps', 20)
    num_images_per_prompt = messages.get('imgNumber', 3)
    guidance_scale = messages.get('guidance_scale', 8.0)
    controlnet_conditioning_scale = messages.get('controlnet_conditioning_scale', 0.6)
    sd_parameter = {
        'prompt': prompt,
        'negative_prompt': negative_prompt,
        'height': height,
        'width': width,
        'num_inference_steps': num_inference_steps,
        'num_images_per_prompt': num_images_per_prompt,
        'guidance_scale': guidance_scale,
        'controlnet_conditioning_scale': controlnet_conditioning_scale
    }
    img_header, img = img
    try:
        img = get_img(img)
    except OSError:
        result_json = {"code": '000003', "msg": "miss image data"}
        return result_json

    user_img = np.asarray(load_image(img))
    image = cv2.Canny(user_img, 100, 200)
    image = image[:, :, None]
    image = np.concatenate([image, image, image], axis=2)
    image = Image.fromarray(image)
    sd_parameter.update({'image': image})
    images = pipe(**sd_parameter).images
    img_list = []
    for each_img in images:
        buff = io.BytesIO()
        each_img.save(buff, format='JPEG')
        img_base = base64.b64encode(buff.getvalue())
        img_list.append(img_header + ',' + str(img_base, encoding='utf-8'))
    result_json = {
        "success": True,
        "errCode": "string",
        "errMsg": "string",
        "totalRows": 0,
        "pageNo": 0,
        "pageSize": 0,
        "totalPages": 0,
        "data": {
            "imgList": img_list
        }
    }
    print('图生图耗时：{}, 生成{}张！'.format(time.time() - start_time, num_images_per_prompt).center(50, '='))
    return json.dumps(result_json, ensure_ascii=False)


if __name__ == '__main__':
    image_device = 'cuda:1'
    control_net = ControlNetModel.from_pretrained("pretrain_weight/controlnet-canny-sdxl-1.0",
                                                  torch_dtype=torch.float16)
    vae = AutoencoderKL.from_pretrained("pretrain_weight/sdxl-vae", torch_dtype=torch.float16)
    pipe = StableDiffusionXLControlNetPipeline.from_single_file(
        r'sd_weight/lbedobaseXL_v11.safetensors',
        controlnet=control_net,
        vae=vae,
        torch_dtype=torch.float16,
        cache_dir='sd_weight',
        local_files_only=False
    ).to(image_device)
    app.run('0.0.0.0', port=49000, debug=False, threaded=True)`
request image is base64

**Comment by TheHonestBob** [comment] 2023-11-10 09:27
> hi @TheHonestBob
> 
> I don't think you code matches with the stack trace :) .... would you be able to provide or recreate the code example that will cause this same error?
> 
> Thanks!
> 
> YiYi

I have tried to modify it several times and found that the code format is always incorrect, which makes me very sorry

**Comment by TheHonestBob** [comment] 2023-11-10 09:37
> self.step_index



> ah don't be sorry! :) I don't think this is something we can reproduce on our end anyway
> 
> it is a little bit out of scope for me but I wonder if this is due to the pipeline did not reset the the `self.step_index` between the requests?

I really remember what you said. There is indeed a problem with assigning class attributes in multiprocessing or multithreading. Do you have any good suggestions

**Comment by TheHonestBob** [comment] 2023-11-11 06:08
> > self.step_index
> 
> > ah don't be sorry! :) I don't think this is something we can reproduce on our end anyway
> > it is a little bit out of scope for me but I wonder if this is due to the pipeline did not reset the the `self.step_index` between the requests?
> 
> I really remember what you said. There is indeed a problem with assigning class attributes in multiprocessing or multithreading. Do you have any good suggestions

 have a good solution, which is to define the step variable in the self. scheduler class using threading. local(). Here is a simple example
`
class Scheduler:
    def __init__(self):
        self._step = threading.local()
        self._step.step = None
    
    def _init_step_index(self):
        self._step.step = 0
        
    @property
    def step(self):
        return self._step.step
    
    def step_process(self):
        
        self._step.step += 1
`

**Comment by TheHonestBob** [comment] 2023-11-11 06:13
> have a good solution, which is to define the step variable in the self. scheduler class using threading. local(). Here is a simple example ` class Scheduler: def **init**(self): self._step = threading.local() self._step.step = None
> 
> ```
> def _init_step_index(self):
>     self._step.step = 0
>     
> @property
> def step(self):
>     return self._step.step
> 
> def step_process(self):
>     
>     self._step.step += 1
> ```

have a good solution, which is to define the step variable in the self. scheduler class using threading. local(). Here is a simple example
`
class Scheduler:
def init(self):
self._step = threading.local()
self._step.step = None

def _init_step_index(self):
    self._step.step = 0
    
@property
def step(self):
    return self._step.step

def step_process(self):
    
    self._step.step += 1

**Comment by TheHonestBob** [comment] 2023-11-11 06:14
> ah don't be sorry! :) I don't think this is something we can reproduce on our end anyway
> 
> it is a little bit out of scope for me but I wonder if this is due to the pipeline did not reset the the `self.step_index` between the requests?

have a good solution, which is to define the step variable in the self. scheduler class using threading. local(). Here is a simple example
`
class Scheduler:
def init(self):
self._step = threading.local()
self._step.step = None

def _init_step_index(self):
    self._step.step = 0
    
@property
def step(self):
    return self._step.step

def step_process(self):
    
    self._step.step += 1

**Comment by yiyixuxu** [comment] 2023-11-11 06:34
oh nice!

**Comment by TheHonestBob** [comment] 2023-11-13 07:43
> oh nice!

May I ask if the official will fix all schedulers for this issue? Personally, I believe it is necessary

**Comment by babyta** [comment] 2023-11-13 11:12
same error，can yo help me?
latents = scheduler.step(noise_pred, i, latents)["prev_sample"]

**Comment by TheHonestBob** [comment] 2023-11-13 11:46
> same error，can yo help me? latents = scheduler.step(noise_pred, i, latents)["prev_sample"]

I have already resolved it. As you can see from my previous discussion, the main reason is the issue of variable sharing in multithreading

**Comment by yiyixuxu** [comment] 2023-11-13 18:42
cc @patrickvonplaten here
do we need to make sure the pipelines work with multithreading? seems like the step counter won't work as it is

**Comment by patrickvonplaten** [comment] 2023-11-14 10:24
I think that's def low-prio! Python by design doesn't work well in multi-threading applications (GIL-lock) so I don't think we need to support it here.

**Comment by yiyixuxu** [comment] 2023-11-17 20:35
@TheHonestBob 

can I close the issue here? seems like you were able to fix it on your end:) 

YiYi

**Closed** 2023-11-18 00:58 UTC
Labels: bug

**Comment by babyta** [comment] 2024-01-09 09:26
> > ah don't be sorry! :) I don't think this is something we can reproduce on our end anyway
> > it is a little bit out of scope for me but I wonder if this is due to the pipeline did not reset the the `self.step_index` between the requests?
> 
> have a good solution, which is to define the step variable in the self. scheduler class using threading. local(). Here is a simple example ` class Scheduler: def init(self): self._step = threading.local() self._step.step = None
> 
> def _init_step_index(self): self._step.step = 0
> 
> @Property def step(self): return self._step.step
> 
> def step_process(self):
> 
> ```
> self._step.step += 1
> ```

Hello, I encountered a similar problem recently. I built a demo with Gradio, but this problem also occurs when multiple people use it. Is there a more specific method? I don’t understand this very well. I am a beginner.

**Comment by dummyuser-123** [comment] 2024-10-03 12:08
@TheHonestBob can you please elaborate more about where and what changes has to made in the schedular script, so that it can work in multi-thread scenario.

**Comment by babyta** [comment] 2024-10-03 12:08
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
