### ISSUE TITLE
None of the pipelines will load anymore

### ISSUE THREAD

**Issue by BlakeOne** [huggingface/diffusers#6431] opened 2024-01-02 23:39 UTC
### Describe the bug

None of the pipelines will load as of today. The call to `from_pretrained` never returns as it is apparently now unable to fetch needed files from huggingface. I tried with and without using a HF secret key and the result is the same. I've been using various pipelines regularly up until today without issue, including as recently as yesterday.

### Reproduction

It's easy to reproduce, just pick any pipeline and try the example in its documentation. I've tried several today, including ones that I was using yesterday like the SVD pipeline, and none of them work anymore...

### System Info

Google Colab with the latest diffusers, transformers, and accelerate packages installed. I also tried locally on my MacBook.

**Comment by BlakeOne** [comment] 2024-01-03 00:49
Update: I tried git cloning the hugging face repo of one of the pipelines (SVD XT) and the pipeline is now working using my local copy of the model files. However it would OC be super impractical to have to do this for every pipeline so hopefully this can still be fixed.

**Comment by sanjinmehic** [comment] 2024-01-03 06:32
I am experiencing the same thing today. What I was running yesterday won't load. When I run: 

`from diffusers import (
    StableDiffusionPipeline,
    StableDiffusionControlNetPipeline,
    ControlNetModel,
    PNDMScheduler

)

controlnet_model = "lllyasviel/sd-controlnet-canny"
sd_model = "Lykon/DreamShaper"

controlnet = ControlNetModel.from_pretrained(
    controlnet_model,
    torch_dtype=torch.float16
)

pipe = StableDiffusionControlNetPipeline.from_pretrained(
    sd_model,
    controlnet=controlnet,
    torch_dtype=torch.float16
)

pipe.scheduler = PNDMScheduler.from_config(pipe.scheduler.config)
pipe.enable_model_cpu_offload()`

it gets hung up at a "Fetching 15 files: 0%..." step.

I'm also running on Colab notebooks, and pip installed the latest versions.

**Comment by notsk11** [comment] 2024-01-03 08:08
Its getting stuck at loading pipeline "Fetching 15 files: 0%." or idk downloading

**Comment by DN6** [comment] 2024-01-03 08:36
Hi @BlakeOne I'm unable to reproduce this. Are you still seeing an error when trying to download the model?

**Comment by notsk11** [comment] 2024-01-03 08:42
![image](https://github.com/huggingface/diffusers/assets/153056264/c46ec62e-b014-4114-bdf7-b457abc0fc9a)

**Comment by DN6** [comment] 2024-01-03 10:39
Hi @BlakeOne are you still observing this issue? I'm unable to reproduce on my end.

**Comment by DN6** [comment] 2024-01-03 10:40
@notsk11 Which version of diffusers are you using?

**Comment by joaomsimoes** [comment] 2024-01-03 11:00
True, the version 0.25.0 is not loading the models. Using the 0.24.0 is working fine

**Comment by notsk11** [comment] 2024-01-03 11:48
> @notsk11 Which version of diffusers are you using? And are you observing the same issue outside of Colab? Could you run `diffusers-cli env` and share the output?

![image](https://github.com/huggingface/diffusers/assets/153056264/6b857586-9d48-4977-b636-4b7fbb0a140e)

**Comment by DN6** [comment] 2024-01-03 12:04
Hmm so it might be a Colab issue, I was able to reproduce it. When I run locally I'm able to download the models using the exact same environment.

**Comment by BlakeOne** [comment] 2024-01-03 16:06
When I try it locally I get this error:

`python3.10/site-packages/huggingface_hub/utils/_http.py", line 78, in send
    raise OfflineModeIsEnabled(
huggingface_hub.utils._http.OfflineModeIsEnabled: Cannot reach https://huggingface.co/api/models/stabilityai/stable-video-diffusion-img2vid-xt: offline mode is enabled. To disable it, please unset the `HF_HUB_OFFLINE` environment variable.`

**Comment by KevinJBoyer** [comment] 2024-01-03 16:18
Confirming I also see `from_pretrained` hang indefinitely in Colab, usually in some kind of threading-related function. Can reproduce it via the `Diffusers.ipynb` here: https://colab.research.google.com/github/huggingface/notebooks/blob/main/diffusers/diffusers_intro.ipynb#scrollTo=PzW5ublpBuUt where it will hang on `image_pipe = DDPMPipeline.from_pretrained("google/ddpm-celebahq-256")`

**Comment by yinglingyang** [comment] 2024-01-04 04:33
Same here. I cannot download SDXL model using from_pretrained() in colab. It stuck at 12% forever. Someone help!

**Comment by lardratboy** [comment] 2024-01-04 04:45
I'm having the problem as well. A possible clue that I noticed is that after stopping the cell, and attempting simply calling userdata.get('HF_TOKEN') in another cell causes a similar stall. If I run that cell after I first start the notebook it functions, it only stalls after the problem in the from_pretrained cell.

**Comment by sayakpaul** [comment] 2024-01-04 05:19
Seems to be a Colab specific problem as commented on the thread. We have informed the concerned team and will get back once we have an answer.

**Comment by notsk11** [comment] 2024-01-04 10:10
> ### Describe the bug
> None of the pipelines will load as of today. The call to `from_pretrained` never returns as it is apparently now unable to fetch needed files from huggingface. I tried with and without using a HF secret key and the result is the same. I've been using various pipelines regularly up until today without issue, including as recently as yesterday.
> 
> ### Reproduction
> It's easy to reproduce, just pick any pipeline and try the example in its documentation. I've tried several today, including ones that I was using yesterday like the SVD pipeline, and none of them work anymore...
> 
> ### Logs
> _No response_
> 
> ### System Info
> Google Colab with the latest diffusers, transformers, and accelerate packages installed. I also tried locally on my MacBook.
> 
> ### Who can help?
> _No response_

https://github.com/huggingface/diffusers/issues/6446#issuecomment-1876407646

this is the solution i tried and its working

**Comment by JhonDan1999** [comment] 2024-01-05 07:47
I think something is changing in the Google Colab environment because the same code was working perfectly fine last week for downloading the stable diffusion XL model. However, now it is stuck at downloading just 19 files, with 0% progress. I tried adding the Hugging Face API key tokens in the Colab settings, but it didn't work!

**Comment by sayakpaul** [comment] 2024-01-05 07:49
https://github.com/huggingface/huggingface_hub/pull/1953

**Comment by Wauplin** [comment] 2024-01-05 09:37
Thanks everyone for reporting and sorry for the inconvenience. I have been able to reproduce the issue and created PR https://github.com/huggingface/huggingface_hub/pull/1953 to fix it. The plan is to make a hot-fix release once it's merged and make it the default in google colab. In the meantime, a temporary solution is to install a different version of `huggingface_hub` before executing any code. More details in https://github.com/huggingface/huggingface_hub/pull/1953#issuecomment-1878364894.

**Closed** 2024-01-07 15:35 UTC
Labels: bug

**Comment by Wauplin** [comment] 2024-01-12 08:45
**Update:** `huggingface_hub 0.20.2` is now the default version on Google Colab, meaning this issue should be fixed for everyone without having to upgrade (see https://github.com/googlecolab/colabtools/issues/4272#issuecomment-1887683158).
