### ISSUE TITLE
LoRA Still Influencing Output Despite Setting "scale" to 0

### ISSUE THREAD

**Issue by Linaqruf** [huggingface/diffusers#4751] opened 2023-08-24 05:41 UTC
Hi, thanks and great job for implementing Kohya LoRA format into diffusers. However, I'm running into an issue where the LoRA settings don't seem to be working as described in the documentation.

According to the [official documentation](https://huggingface.co/docs/diffusers/training/lora#dreambooth-inference), setting the scale value in `cross_attention_kwargs = {'scale' : 0}` should completely nullify the effect of LoRA. The model should rely only on its base weights.

>_💡 A scale value of 0 is the same as not using your LoRA weights and you’re only using the base model weights, and a scale value of 1 means you’re only using the fully finetuned LoRA weights. Values between 0 and 1 interpolates between the two weights._

So I thought this is interpolation weight merging, similar to Kohya, Auto1111 or ComfyUI implementation. However In my case, even after setting `cross_attention_kwargs =  {'scale' : 0}`, I've noticed that LoRA still appears to influence the results. This seems contradictory to what the documentation states.
| Description  | Image  |
|--------------|--------|
| Scale 1      | ![scale 1](https://github.com/huggingface/diffusers/assets/50163983/1b6338ea-c553-4d35-8e16-8a396c380283)       |
| Scale 0.5    | ![scale 0.5](https://github.com/huggingface/diffusers/assets/50163983/17258e8f-83b7-421d-b666-1707f7622570) |
| Scale 0      | ![scale 0](https://github.com/huggingface/diffusers/assets/50163983/8b9f8536-bf55-4959-a502-3c7617099abd)     |
| No Lora      | ![no lora](https://github.com/huggingface/diffusers/assets/50163983/1bf8775a-30ec-465e-b203-1d6e6160b86c)     |

Is this a known issue, or am I possibly misinterpreting how to set up the feature correctly? I'd appreciate any guidance or clarification.

I wrote a notebook to reproduce this issue here
https://colab.research.google.com/drive/1P_PVUoyrPzb15EK9G1FFZIH3YnpwnPaC

**Comment by Linaqruf** [comment] 2023-08-24 05:54
Hi @sayakpaul

**Comment by sayakpaul** [comment] 2023-08-24 05:58
Thanks for reporting this. The issue is very well described. Will look into it :-)

**Comment by sayakpaul** [comment] 2023-08-25 04:36
We are doing two major refactors just as an FYI which might influence this issue:

#4473 
#4765

**Comment by sayakpaul** [comment] 2023-08-25 09:02
I think I understand what's happening here. Let me try to elaborate in a lucid manner. 

We support LoRA attention processors for the attention modules only at the moment. In those processors, you would find a `scale` argument in their `__call__()` methods. Here's an example:

https://github.com/huggingface/diffusers/blob/470d51c8edf130b0aa75e915ce331b80206f3ac5/src/diffusers/models/attention_processor.py#L573

However, non diffusers LoRAs might also contain additional modules concerning different network blocks that don't necessarily correspond to attention always. Such as: conv, mlp, etc. 

To support those, we rely on: `LoRACompatibleLinear` and `LoRACompatibleConv`. 

https://github.com/huggingface/diffusers/blob/470d51c8edf130b0aa75e915ce331b80206f3ac5/src/diffusers/models/lora.py#L101

https://github.com/huggingface/diffusers/blob/470d51c8edf130b0aa75e915ce331b80206f3ac5/src/diffusers/models/lora.py#L80

Their call arguments don't have `scale` argument. This is why even when we specify the `scale` argument via `cross_attention_kwargs` the non-attention LoRA modules still remain effective. This will very likely be fixed in https://github.com/huggingface/diffusers/pull/4765. 

I hope this elaboration helps to understand what is happening here. 

Cc: @patrickvonplaten @isidentical @apolinario

**Comment by Linaqruf** [comment] 2023-08-25 10:49
I see, that makes sense. I thought `scale` is the same as `multiplier` in their implementation. 

https://github.com/kohya-ss/sd-scripts/blob/sdxl/networks/lora_diffusers.py#L156-L172

Looking forward into the fix!

**Comment by patrickvonplaten** [comment] 2023-08-25 18:34
That's exactly right @sayakpaul - only that it will probably not directly be fixed in #4765, but we can open a new PR to look into how to fix it :-)

**Comment by sayakpaul** [comment] 2023-08-31 09:08
@Linaqruf https://github.com/huggingface/diffusers/pull/4842#issuecomment-1699732055

**Closed** 2023-09-04 21:52 UTC

**Comment by Linaqruf** [comment] 2023-09-05 05:30
Thanks @sayakpaul, @patrickvonplaten, and sorry; I totally forgot about this issue. I was doing other stuff last week. 😅

This is great; not only is the scale: 0 problem fixed, but the implementation is also 1:1 with the [Kohya LoRA loader.](https://huggingface.co/spaces/Linaqruf/Animagine-XL/raw/main/lora_diffusers.py) I compared both implementations and the result is about the same.

| Scale | Diffusers | Kohya |
|-------|-----------|-------|
| 1     | ![diffusers1](https://github.com/huggingface/diffusers/assets/50163983/31959deb-da87-4891-a30f-67e9b93d17aa) | ![kohya1](https://github.com/huggingface/diffusers/assets/50163983/346a67cf-7a9e-425e-b6d0-e5384e31f539)     |
| 0.5   | ![diffusers0.5](https://github.com/huggingface/diffusers/assets/50163983/3677cb58-9961-4f89-ba58-55b282588d8c) | ![kohya0.5](https://github.com/huggingface/diffusers/assets/50163983/eb652305-1652-45b6-b307-d923837f77c2) |
| 0     | ![diffusers0](https://github.com/huggingface/diffusers/assets/50163983/5d8af1d6-17fe-46fe-8e6a-fa1bf0274915)   | ![kohya0](https://github.com/huggingface/diffusers/assets/50163983/2a442985-4927-4e29-9790-49e05bddb12e)   |
| None  | ![diffusersNone](https://github.com/huggingface/diffusers/assets/50163983/fa8af467-b718-463d-a6a7-d82bf2efc47a) | ![kohyaNone](https://github.com/huggingface/diffusers/assets/50163983/9c801519-9a63-4592-ae82-4d7e0963b171)  |

I wrote new notebook to reproduce this result
1. With Diffusers 0.21.0.dev = https://colab.research.google.com/drive/1gasmUzOSTrMcwhPngNCtlSMa2fTkyyOE
2. With Kohya LoRA Loader = https://colab.research.google.com/drive/1siic-5ylI5Zu_ROrE-cLPUM_l1SENLZZ
