### ISSUE TITLE
"Input is in incorrect format." incorrect error message

### ISSUE THREAD

**Issue by LWprogramming** [huggingface/diffusers#8373] opened 2024-05-31 17:27 UTC
### Describe the bug

https://github.com/huggingface/diffusers/blob/983dec3bf787c064ed57f2621c9b7375d443f746/src/diffusers/image_processor.py#L536

`f"Input is in incorrect format. Currently, we only support {', '.join(supported_formats)}"` fails because [`supported_formats`](https://github.com/huggingface/diffusers/blob/983dec3bf787c064ed57f2621c9b7375d443f746/src/diffusers/image_processor.py#L839) is a list of types and not strings. Gets `TypeError: sequence item 0: expected str instance, type found`. Ran into this when trying to debug why the type I'm using in my code is wrong but the error message itself errors

### Reproduction

```
from diffusers.image_processor import VaeImageProcessor

mask_processor = VaeImageProcessor(
    vae_scale_factor=8, do_normalize=False, do_binarize=True, do_convert_grayscale=True
)
height = 1024
width = 1024
mask_image = "some random bad type here"
resize_mode = "default"
crops_coords = None
mask_processor.preprocess(
    mask_image, height=height, width=width, resize_mode=resize_mode, crops_coords=crops_coords
)
```

### System Info

```
- 🤗 Diffusers version: 0.28.0
- Platform: Linux-5.15.0-1060-gcp-x86_64-with-glibc2.29
- Running on a notebook?: No
- Running on Google Colab?: No
- Python version: 3.8.10
- PyTorch version (GPU?): 2.3.0+cu121 (False)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Huggingface_hub version: 0.23.2
- Transformers version: not installed
- Accelerate version: not installed
- PEFT version: not installed
- Bitsandbytes version: not installed
- Safetensors version: 0.4.3
- xFormers version: not installed
- Accelerator: NA
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>
```

### Who can help?

@yiyixu

**Comment by sayakpaul** [comment] 2024-06-01 06:49
Cc: @yiyixuxu

**Comment by DN6** [comment] 2024-07-05 05:12
Closing as it appears the issue is fixed.

**Closed by DN6** 2024-07-05 05:12 UTC
Labels: bug
