### ISSUE TITLE
How to add a lora model in controlnet pipeline?

### ISSUE THREAD

**Issue by ymzlygw** [huggingface/diffusers#2714] opened 2023-03-17 00:58 UTC
**Describe the solution you'd like**
Just like diffusionpipeline, we can  simplely add any lora model.

or Can I do it like this using 'StableDiffusionControlNetPipeline'?:   
 
    pipe = StableDiffusionControlNetPipeline.from_pretrained()
    pipe.unet.load_attn_procs(lora_model_path)

**Comment by ymzlygw** [comment] 2023-03-17 01:09
Can I do it like this using 'StableDiffusionControlNetPipeline'?:   
 
    pipe = StableDiffusionControlNetPipeline.from_pretrained()
    pipe.load_attn_procs(lora_model_path)

**Comment by takuma104** [comment] 2023-03-17 14:55
Hi @ymzlygw ,

I think `pipe.unet.load_attn_procs(lora_model_path)` should work fine. As for the example of MultiControlNet, 
<img width='256' src='https://user-images.githubusercontent.com/10776/225939458-2f2d85ca-4fbe-4239-8043-697dbdcfbc27.png'/>

using `pipe.unet.load_attn_procs("sayakpaul/sd-model-finetuned-lora-t4")` (Pokemon-like style) resulted in an image similar to this.

<img width='256' src='https://user-images.githubusercontent.com/10776/225939429-827cce74-3b82-49df-a987-a42c24a1fdd2.png'/>

I'm surprised that it worked exactly as intended :)

**Comment by sayakpaul** [comment] 2023-03-21 03:53
Thanks, @takuma104!

Closing this issue as it seems to have got resolved. Feel free to re-open in case of problems.

**Closed by sayakpaul** 2023-03-21 03:53 UTC
