### ISSUE TITLE
from_pretrained can't work in Google Colab

### ISSUE THREAD

**Issue by WiNE-iNEFF** [huggingface/diffusers#6441] opened 2024-01-03 20:36 UTC
### Describe the bug

I try to load model using ddpmpipeline.from_pretrained and loading model stop in line "fetching files"

### Reproduction

I try use all diffusers start from 0.24.1 to last
`
image_pipe = DDPMPipeline.from_pretrained("google/ddpm-ema-church-256").to(device)
`
And when collab load code his starts loading files forever

### System Info

Google colab
Diffusers Library all version start from 0.24.1

### Who can help?

@yiyixuxu @DN6

**Comment by WiNE-iNEFF** [comment] 2024-01-03 20:43
I started getting this error on all my Google collabs after its last update. In this case, all models stop loading exactly at the moment "fetching files"

**Comment by alorthius** [comment] 2024-01-03 20:49
I am facing the same issue in colab with StableDIffusionPipeline / DiffusionPipeline

**Comment by math-rb** [comment] 2024-01-03 23:36
Same issue here. Loading stops when it starts fetching files. Tried both StableDIffusionPipeline and DiffusionPipeline and multiple models.

`from diffusers import StableDiffusionPipeline`
`import torch`
`pipe = StableDiffusionPipeline.from_pretrained(model_path, torch_dtype=torch.float16`)

**Comment by jasonisme123** [comment] 2024-01-04 00:03
You nedd to input your token after "torch_dtype=torch.float16" by using "token=<<input your token here>>

**Comment by maliozer** [comment] 2024-01-04 02:32
Same issue I have just duplicated at https://github.com/huggingface/diffusers/issues/6446

**Comment by maliozer** [comment] 2024-01-04 02:34
I also tried with my old diffusers fork and still same, the issue probably on transformers package but have no idea indeed.

**Comment by sayakpaul** [comment] 2024-01-04 04:12
Hmm this seems to be a problem only on Colab. I tried it on our internal server and on my local machine. It wasn't a problem.

**Comment by DN6** [comment] 2024-01-04 05:42
Issue has been raised on the Colab repo 
https://github.com/googlecolab/colabtools/issues/4272

**Comment by pranauv1** [comment] 2024-01-04 08:26
This might help!
https://github.com/huggingface/diffusers/issues/6446#issuecomment-1876407646

**Comment by sayakpaul** [comment] 2024-01-05 01:11
We're on top of it: https://github.com/huggingface/huggingface_hub/pull/1953. Cc: @Wauplin

**Comment by Wauplin** [comment] 2024-01-05 09:38
Thanks everyone for reporting and sorry for the inconvenience. I have been able to reproduce the issue and created a PR (https://github.com/huggingface/huggingface_hub/pull/1953) to fix it. The plan is to make a hot-fix release once it's merged and make it the default in google colab. In the meantime, a temporary solution is to install a different version of `huggingface_hub` before executing any code. More details in https://github.com/huggingface/huggingface_hub/pull/1953#issuecomment-1878364894.

**Comment by 7iFinalBoSS** [comment] 2024-01-05 15:46
`!pip install -U huggingface_hub`

try this in you colab notebook

**Comment by WiNE-iNEFF** [comment] 2024-01-05 16:54
> !pip install -U huggingface_hub

this not work

**Comment by Wauplin** [comment] 2024-01-12 08:45
**Update:** `huggingface_hub 0.20.2` is now the default version on Google Colab, meaning this issue should be fixed for everyone without having to upgrade (see https://github.com/googlecolab/colabtools/issues/4272#issuecomment-1887683158).

**Closed by Wauplin** 2024-01-12 08:45 UTC
Labels: bug
