### ISSUE TITLE
Merging Audio and Video Tracks with Captions

### ISSUE THREAD

**Issue by andysingal** [huggingface/diffusers#5283] opened 2023-10-03 17:22 UTC
### Describe the bug

I was not able to add transcripts within the video, output mp4 is in audio format
```
Here is the code for reference:
https://colab.research.google.com/drive/1pRFlp1-OVZmRwyGLlMpexe6tSKVAKmwG?usp=sharing 
```

### Reproduction

shared the notebook above

### System Info

colab pro

### Who can help?

@sanchit-gandhi @kashif

**Comment by patrickvonplaten** [comment] 2023-10-04 09:58
We would need a bit more info about what exactly the issue is here @andysingal

**Comment by andysingal** [comment] 2023-10-04 10:16
> We would need a bit more info about what exactly the issue is here @andysingal

Thanks @patrickvonplaten for your response. The issue is, i am able to get the audio from youtube video when merging  i would like transcript within the video similar to Karoke. I was following https://www.digitalocean.com/community/tutorials/how-to-make-karaoke-videos-using-whisper-and-spleeter-ai-tools.
Please let me know if this assists

**Comment by kashif** [comment] 2023-10-04 10:23
i believe your issue is not related to this repository... neither your colab nor this tutorial use diffusers

**Comment by andysingal** [comment] 2023-10-04 10:25
> i believe your issue is not related to this repository... neither your colab nor this tutorial use diffusers

I thought this is related to audio issue? Please advise where i can ask this question?

**Comment by kashif** [comment] 2023-10-04 10:36
as your colab and the above tutorial you linked to are using spleeter and openai whisper, I suggest you open an issue at the appropriate repository or forum etc. related to your problem there. 

Kindly refrain from adding me to issues without due diligence and close this issue as a courtesy.

**Closed** 2023-10-04 10:36 UTC
Labels: bug
