### ISSUE TITLE
DreamBooth training script / FLUX.1 [dev]

### ISSUE THREAD

**Issue by lamm-mit** [huggingface/diffusers#9204] opened 2024-08-16 15:43 UTC
### Describe the bug

Thanks @bghira @sayakpaul for sharing the FLUX DreamBooth training scripts at https://github.com/huggingface/diffusers/blob/main/examples/dreambooth/README_flux.md

I was trying to run the examples and also train on my own data (I have successfully used it to get fine-tunes using SD2.x, SDXL, etc.). While the LoRA training script works, I do not get a reduction in loss and am thinking that no training is happening (loss stays approximately constant, I tried a variety of LRs).

The full fine tune gives me a tensor dimension error:

[..]    latents = latents.view(batch_size, height, width, channels // 4, 2, 2)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: shape '[1, 4, 4, 16, 2, 2]' is invalid for input of size 65536 [...]

The fine tune with text model -train_text_encoder also throws an error message. I was curious if others have tried it or if you know if someone could have another working example that I could try?

Thank you!

Also tagging @linoytsaban who I believe has done some pull requests/bug fixes

### Reproduction

Examples in README: https://github.com/huggingface/diffusers/blob/main/examples/dreambooth/README_flux.md

### System Info

diffusers-0.31.0.dev0

**Comment by sayakpaul** [comment] 2024-08-17 06:42
Cc: @linoytsaban

**Comment by linoytsaban** [comment] 2024-08-19 07:22
hey @lamm-mit! is it possible you're not using the most recent version? merged in https://github.com/huggingface/diffusers/pull/9139

**Comment by lamm-mit** [comment] 2024-08-20 00:24
Thanks for getting back! Yes, I am using the latest merge (pip install from git and downloaded the training scripts directly from there also for my local directory). Any chance you have some loss plots or other data from your run so I can debug? Much appreciated.

**Comment by APannnnnnnnd** [comment] 2024-08-21 09:26
> Thanks for getting back to me @linoytsaban! Yes, I am using the latest merge (pip install from git and downloaded the training scripts directly from there also for my local directory). Any chance you have some loss plots or other data from your run so I can debug? Much appreciated.

So you solved the problem? I'm having the same problem. I haven't got a clue how to fix it yet.

**Comment by lamm-mit** [comment] 2024-08-21 13:19
No, nothing yet. It still does not work. I had a lot of issues and in cases that did run, no training occurred (loss remained ~constant). Thank you everyone for your help to debug these issues.

**Comment by bghira** [comment] 2024-08-21 13:38
here's a flat loss curve on a model that trained really nicely:

![image](https://github.com/user-attachments/assets/8e78dba1-8bda-485a-89a4-42f9eb4aec48)

**Comment by APannnnnnnnd** [comment] 2024-08-22 02:27
> No, nothing yet. It still does not work. I had a lot of issues and in cases that did run, no training occurred (loss remained ~constant). Thank you everyone for your help to debug these issues.

model_pred = FluxPipeline._unpack_latents(
                    model_pred,
                    height=int(model_input.shape[2]) * 8,
                    width=int(model_input.shape[3]) * 8,
                    vae_scale_factor=vae_scale_factor,
                )
[](https://github.com/huggingface/diffusers/pull/9139/files#diff-9e7c4cd1d14324af7039cb97cddfc87763361dfd601f7a7aeae87cafd7c210ad)
I see that the code before the improvement had a * 8, and I didn't get an error after adding the height and width, but I'm not sure if this will cause other new problems.
So why did the source code delete this * 8 later?

**Comment by linoytsaban** [comment] 2024-08-22 05:29
what resolution are you training with @APannnnnnnnd ? 
for debugging purposes, could you try this config? (I used it for a lora that worked well)

```
!accelerate launch train_dreambooth_lora_flux.py \
  --pretrained_model_name_or_path="black-forest-labs/FLUX.1-dev" \
  --dataset_name="dog"\
  --instance_prompt="an sks dog"\
  --output_dir="dog_lora_flux" \
  --mixed_precision="bf16" \
  --optimizer="prodigy" \
  --weighting_scheme="none"\
  --resolution=512 \
  --train_batch_size=1 \
  --repeats=1\
  --learning_rate=1.0\
  --report_to="wandb"\
  --gradient_accumulation_steps=1 \
  --gradient_checkpointing \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --rank=4\
  --max_train_steps=500 \
  --checkpointing_steps=2000 \
  --seed="0"\
  --push_to_hub
```

**Comment by APannnnnnnnd** [comment] 2024-08-22 05:45
> what resolution are you training with @APannnnnnnnd ? for debugging purposes, could you try this config? (I used it for a lora that worked well)
> 
> ```
> !accelerate launch train_dreambooth_lora_flux.py \
>   --pretrained_model_name_or_path="black-forest-labs/FLUX.1-dev" \
>   --dataset_name="dog"\
>   --instance_prompt="an sks dog"\
>   --output_dir="dog_lora_flux" \
>   --mixed_precision="bf16" \
>   --optimizer="prodigy" \
>   --weighting_scheme="none"\
>   --resolution=512 \
>   --train_batch_size=1 \
>   --repeats=1\
>   --learning_rate=1.0\
>   --report_to="wandb"\
>   --gradient_accumulation_steps=1 \
>   --gradient_checkpointing \
>   --lr_scheduler="constant" \
>   --lr_warmup_steps=0 \
>   --rank=4\
>   --max_train_steps=500 \
>   --checkpointing_steps=2000 \
>   --seed="0"\
>   --push_to_hub
> ```

Examples in README: https://github.com/huggingface/diffusers/blob/main/examples/dreambooth/README_flux.md

`export MODEL_NAME="black-forest-labs/FLUX.1-dev"
export INSTANCE_DIR="dog"
export OUTPUT_DIR="trained-flux"

accelerate launch train_dreambooth_flux.py \
  --pretrained_model_name_or_path="./FLUX.1-dev"  \
  --instance_data_dir="mydata" \
  --output_dir="output_dir" \
  --mixed_precision="bf16" \
  --instance_prompt="a photo of sks dog" \
  --resolution=1024 \
  --train_batch_size=1 \
  --gradient_accumulation_steps=4 \
  --learning_rate=1e-4 \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --max_train_steps=500 \
  --validation_prompt="A photo of sks dog in a bucket" \
  --validation_epochs=25 \
  --seed="0" \
`

The example I used, it did have the above problem when training. After I added * 8 to the code there, it didn't give the error. Of course, I'm still debugging the code to fit my own project, but I don't think there will be any more problems.

**Comment by linoytsaban** [comment] 2024-08-22 06:53
hmm I can't seem to reproduce your bug, currently training on 1024 resolution and it works fine https://wandb.ai/linoy/dreambooth-flux-dev-lora/reports/loss-24-08-22-09-51-15---Vmlldzo5MTEyMTY5
```
#!/usr/bin/env bash
!accelerate launch train_dreambooth_lora_flux.py \
  --pretrained_model_name_or_path="black-forest-labs/FLUX.1-dev" \
  --dataset_name="Norod78/Yarn-art-style"\
  --instance_prompt="a puppy, yarn art style"\
  --output_dir="yarn_art_lora_flux" \
  --mixed_precision="bf16" \
  --use_8bit_adam\
  --weighting_scheme="none"\
  --resolution=1024 \
  --train_batch_size=1 \
  --repeats=1\
  --learning_rate=1e-4\
  --guidance_scale=1\
  --report_to="wandb"\
  --gradient_accumulation_steps=1 \
  --gradient_checkpointing \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --guidance_scale=1\
  --rank=4\
  --max_train_steps=700 \
  --checkpointing_steps=2000 \
  --seed="0"\
  --push_to_hub
 ```
for context, [this loss](https://wandb.ai/linoy/dreambooth-flux-dev-lora/reports/loss-24-08-22-09-12-28---Vmlldzo5MTExNjk4) is from another training I just ran, with same config, except different resolution (768) 
didnt crash, and it did converge - 
![image](https://github.com/user-attachments/assets/acc4c9ef-4bb4-4960-b9a7-f54d0c8d309c)

**Comment by APannnnnnnnd** [comment] 2024-08-22 07:19
> hmm I can't seem to reproduce your bug, currently training on 1024 resolution and it works fine so far https://wandb.ai/linoy/dreambooth-flux-dev-lora/reports/loss-24-08-22-09-51-15---Vmlldzo5MTEyMTY5
> 
> ```
> #!/usr/bin/env bash
> !accelerate launch train_dreambooth_lora_flux.py \
>   --pretrained_model_name_or_path="black-forest-labs/FLUX.1-dev" \
>   --dataset_name="Norod78/Yarn-art-style"\
>   --instance_prompt="a puppy, yarn art style"\
>   --output_dir="yarn_art_lora_flux" \
>   --mixed_precision="bf16" \
>   --use_8bit_adam\
>   --weighting_scheme="none"\
>   --resolution=1024 \
>   --train_batch_size=1 \
>   --repeats=1\
>   --learning_rate=1e-4\
>   --guidance_scale=1\
>   --report_to="wandb"\
>   --gradient_accumulation_steps=1 \
>   --gradient_checkpointing \
>   --lr_scheduler="constant" \
>   --lr_warmup_steps=0 \
>   --guidance_scale=1\
>   --rank=4\
>   --max_train_steps=700 \
>   --checkpointing_steps=2000 \
>   --seed="0"\
>   --push_to_hub
> ```
> 
> for context, [this loss](https://wandb.ai/linoy/dreambooth-flux-dev-lora/reports/loss-24-08-22-09-12-28---Vmlldzo5MTExNjk4) is from another training I just ran, with same config, except different resolution (768) didnt crash, and it did converge - ![image](https://private-user-images.githubusercontent.com/57615435/360318877-acc4c9ef-4bb4-4960-b9a7-f54d0c8d309c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMTEwNjAsIm5iZiI6MTcyNDMxMDc2MCwicGF0aCI6Ii81NzYxNTQzNS8zNjAzMTg4NzctYWNjNGM5ZWYtNGJiNC00OTYwLWI5YTctZjU0ZDBjOGQzMDljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDA3MTI0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0OGUzZjRhYWIyMzVmYTRlYTNjY2ZiZDZiYzJiYTVjZDRmZWNjMDdiZGNjYzgyYmZmZDI4NjdmMGEyM2FiZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xQ_Np-X2pTaziQzmW5cCIMcMbvokYk8k-9joOU5RuZ4)

Oh, I see where the difference is, in **train_dreambooth_lora_flux.py**：
`
                model_pred = FluxPipeline._unpack_latents(
                    model_pred,
                    height=int(model_input.shape[2] * vae_scale_factor / 2),
                    width=int(model_input.shape[3] * vae_scale_factor / 2),
                    vae_scale_factor=vae_scale_factor,
                )
`
The value of vae_scale_factor should be 16 by default.
But in the file **train_dreambooth_flux.py** that I'm running,
`
                model_pred = FluxPipeline._unpack_latents(
                    model_pred,
                    height=int(model_input.shape[2]),
                    width=int(model_input.shape[3]),
                    vae_scale_factor=vae_scale_factor,
                )
`
There is no * 8 in the source code. After I added * 8 to height and width, there was no error.

Still, thanks for your help and advice.

**Comment by linoytsaban** [comment] 2024-08-22 07:20
oh ok I see, let me look into the dreambooth script as well!

**Comment by int2char** [comment] 2024-08-23 02:43
change this line to, works for me

model_pred = FluxPipeline._unpack_latents(
                    model_pred,
                    height=int(pixel_values.shape[2]),
                    width=int(pixel_values.shape[3]),
                    vae_scale_factor=vae_scale_factor,
                )

**Comment by lamm-mit** [comment] 2024-08-24 13:58
Hi everyone, glad to see all these ideas. I updated my local diffusers branch and while it ran with the version from ~one week ago (without successful training), now training does not even start. Not sure what changed, but I the code now just terminates without ever starting to train. I check on two machines, same behavior.

[...]

subprocess.CalledProcessError: Command '['/home/mbuehler/miniconda3/envs/PyTorch/bin/python', 'train_dreambooth_lora_flux.py', '--pretrained_model_name_or_path=black-forest-labs/FLUX.1-dev', '--dataset_name=lamm-mit/trained_flux_V10_data', '--caption_column=caption', '--image_column=image', '--instance_prompt=<leaf microstructure>', '--output_dir=trained_flux_V10', '--mixed_precision=bf16', '--rank=16', '--repeats=1', '--use_8bit_adam', '--weighting_scheme=none', '--resolution=1024', '--train_batch_size=1', '--gradient_accumulation_steps=4', '--gradient_checkpointing', '--guidance_scale=1', '--learning_rate=1e-4', '--lr_scheduler=constant', '--weighting_scheme=logit_normal', '--lr_warmup_steps=0', '--max_train_steps=700', '--checkpointing_steps=700', '--report_to=wandb', '--seed=3234290']' returned non-zero exit status 1.

**Closed** 2024-08-26 11:59 UTC
Labels: bug

**Comment by sayakpaul** [comment] 2024-08-26 12:10
cc: @linoytsaban

**Comment by linoytsaban** [comment] 2024-08-26 12:20
@lamm-mit could you please share the whole traceback of the error you're getting?

**Comment by lamm-mit** [comment] 2024-08-26 12:20
Thanks @sayakpaul and @linoytsaban! To clarify, there are two issues: With the latest from-github-installed version of diffusers, the training script does not run at all. Second, the original issue that the model does not train, still persists. There seem to be others with similar issues (see other issues raised).

**Comment by lamm-mit** [comment] 2024-08-26 12:29
> @lamm-mit could you please share the whole traceback of the error you're getting?

08/26/2024 08:25:09 - INFO - __main__ - Distributed environment: DistributedType.NO
Num processes: 1
Process index: 0
Local process index: 0
Device: cuda

Mixed precision type: bf16

You set `add_prefix_space`. The tokenizer needs to be converted from the slow tokenizers
You are using a model of type clip_text_model to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
You are using a model of type t5 to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
Downloading shards: 100%|████████████████████████| 2/2 [00:00<00:00, 113.38it/s]
Loading checkpoint shards: 100%|██████████████████| 2/2 [01:47<00:00, 53.97s/it]
Fetching 3 files: 100%|██████████████████████████| 3/3 [00:00<00:00, 149.66it/s]
{'axes_dims_rope'} was not found in config. Values will be initialized to default values.
Traceback (most recent call last):
  File "/home/mbuehler/miniconda3/envs/PyTorch/bin/accelerate", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/mbuehler/miniconda3/envs/PyTorch/lib/python3.11/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/home/mbuehler/miniconda3/envs/PyTorch/lib/python3.11/site-packages/accelerate/commands/launch.py", line 1106, in launch_command
    simple_launcher(args)
  File "/home/mbuehler/miniconda3/envs/PyTorch/lib/python3.11/site-packages/accelerate/commands/launch.py", line 704, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/mbuehler/miniconda3/envs/PyTorch/bin/python', 'train_dreambooth_lora_flux.py', '--pretrained_model_name_or_path=black-forest-labs/FLUX.1-dev', '--dataset_name=lamm-mit/leaf_LoRA_FLUX_V30_data', '--caption_column=caption', '--image_column=image', '--instance_prompt=leaf microstructure', '--output_dir=leaf_LoRA_FLUX_V30', '--mixed_precision=bf16', '--rank=16', '--resolution=512', '--train_batch_size=1', '--gradient_accumulation_steps=4', '--gradient_checkpointing', '--learning_rate=2e-4', '--lr_scheduler=constant', '--weighting_scheme=logit_normal', '--lr_warmup_steps=0', '--max_train_steps=500', '--checkpointing_steps=100', '--report_to=wandb', '--seed=3234290']' died with <Signals.SIGKILL: 9>.

**Comment by bghira** [comment] 2024-08-26 12:45
how much system memory do you have?

**Comment by bghira** [comment] 2024-08-26 12:47
essentially SIGKILL: 9 means your process was killed **by your operating system** which is because it's consuming a lot of memory

**Comment by bghira** [comment] 2024-08-26 13:03
the only things that changed (it's a single commit) are the text encoder training logic. if you're using `--train_text_encoder`, remove that, since now it properly works

but also it's extended teh sequence length from 77 to 512, which you cannot change without breaking the model. if this is the reason it doesn't work, the only solution is more system memory.

unfortunately, because the fixes are all correctness related, there is nothing that can be changed other than the underlying hardware.

**Comment by lamm-mit** [comment] 2024-08-26 13:38
Thanks for the additional explanation, as this helps me understand what is going on, especially the larger memory need. I moved to a system with 64 GB RAM and it is training. I'll check later on to see if the training now works. 

I have not been using --train_text_encoder, even though that had failed earlier. I will leave it out for the initial tests to see if I get some positive training outcome.

**Comment by lamm-mit** [comment] 2024-08-26 19:23
Update, I repeated the training (with much higher memory footprint due to the higher sequence length) but see the same results: No response to my training data. Any ideas? Any help would be much appreciated. 

!accelerate launch train_dreambooth_lora_flux.py \
      --pretrained_model_name_or_path="{pretrained_model_name_or_path}" \
      --dataset_name="lamm-mit/{instance_output_dir}_data" \
      --caption_column='caption' \
      --image_column='image' \
      --instance_prompt="{instance_prompt}" \
      --output_dir="{instance_output_dir}" \
      --mixed_precision="bf16" \
      --rank=64 \
      --repeats=1 \
      --use_8bit_adam \
      --weighting_scheme="none" \
      --resolution=1024 \
      --train_batch_size=1 \
      --gradient_accumulation_steps=8 \
      --gradient_checkpointing \
      --learning_rate=5e-5 \
      --hub_model_id={repo_id} \
      --lr_scheduler="constant" \
      --lr_warmup_steps=0 \
      --max_train_steps=500 \
      --checkpointing_steps=100 \
      --report_to="wandb" \
      --seed="3234290"
