### ISSUE TITLE
Issue during training diffusion model with custom dataset

### ISSUE THREAD

**Issue by neramas1221** [huggingface/diffusers#3738] opened 2023-06-10 19:49 UTC
While training the CompVis/stable-diffusion-v1-4 model I get an issue of a byte error with the images 

`UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f57670893a0>`

I get the same issue with the runwayml/stable-diffusion-v1-5 model1

There where no issues when I pushed my dataset to Hugging Face so I'm unsure what could be casuing this? 

I tried pushing a new version of the dataset to Hugging Face but still get the same issue.

Thank you for any help

Cheers

**Comment by patrickvonplaten** [comment] 2023-06-12 15:39
Hey @neramas1221, 

Could you attach a reproducible code snippet?

**Comment by neramas1221** [comment] 2023-06-12 20:18
Hi @patrickvonplaten, 

I've attached the code I'm using in google colab to run the model and will make the dataset public on hugging face so you can try for yourself


```python
!pip install git+https://github.com/huggingface/diffusers.git
!git clone https://github.com/huggingface/diffusers.git
!pip install -U -r /content/diffusers/examples/text_to_image/requirements.txt

!accelerate config default

!huggingface-cli login

from google.colab import drive
drive.mount('/content/gdrive/', force_remount=True)

MODEL_NAME= "CompVis/stable-diffusion-v1-4"
dataset_name="Neramas1221/mtg-image-data"

!accelerate launch --mixed_precision="fp16"  /content/diffusers/examples/text_to_image/train_text_to_image.py \
  --pretrained_model_name_or_path=$MODEL_NAME \
  --dataset_name=$dataset_name \
  --use_ema \
  --resolution=512 --center_crop --random_flip \
  --train_batch_size=1 \
  --gradient_accumulation_steps=4 \
  --gradient_checkpointing \
  --max_train_steps=150000 \
  --learning_rate=5e-6 \
  --max_grad_norm=1 \
  --lr_scheduler="constant" --lr_warmup_steps=0 \
  --output_dir="/content/gdrive/MyDrive/mtg-sd/test6" 
```

**Comment by sayakpaul** [comment] 2023-06-15 14:15
Could you give us a map of how the data folder is represented? I am guessing there's an incompatible image file there somewhere.

**Comment by neramas1221** [comment] 2023-06-19 09:13
The dataset on hugging face is a set of 7 parquet files, originally before pushing the dataset to hugging face using the guide [here](https://huggingface.co/docs/datasets/upload_dataset) this data set was in the format of a folder of images with a csv file with the description of the images and the file location.

**Comment by sayakpaul** [comment] 2023-06-20 05:38
If you could prepare a dataset representing the similar one that you have (and are facing issues with), I can delve deeper. But without an actual dataset to start my debugging with, I don't see anything actionable here, sorry.

**Comment by neramas1221** [comment] 2023-06-21 11:01
@sayakpaul The dataset can be found [here](https://huggingface.co/datasets/Neramas1221/mtg-image-data/tree/main/data) on hugging face or I can share the original dataset with you from my google drive if thats easier

**Comment by sayakpaul** [comment] 2023-06-22 04:09
Thanks for sharing!

I used your dataset and the dataset related utilities from the training script (`train_text_to_image.py`) and I was able to loop through the dataloader: https://colab.research.google.com/gist/sayakpaul/e12de50e7197639c1d84a87d3d66e5f5/scratchpad.ipynb

Am I missing out on anything here?

**Comment by neramas1221** [comment] 2023-06-22 11:32
The problem is when I try to train the model using the examples given [here](https://github.com/huggingface/diffusers/tree/main/examples/text_to_image) I get the Byte IO error like shown above, if the data is fine and can be loaded in to the dataloader script then Im more confused about what could be going wrong. I provided a code snippet earlier can you try that and see if you get the same error?

**Comment by sayakpaul** [comment] 2023-06-22 11:39
It could be because there's some corruption in the dataset itself. So, I would try to limit the dataset and train on the slices just to confirm this.

I am confident that this issue doesn't stem from the training script itself (as I ran the script about an hour ago from now). That is why, I am going to close this thread. Do feel free to keep this thread updated with your findings.

**Closed by sayakpaul** 2023-06-22 11:39 UTC
