### ISSUE TITLE
if "text_embeds" not in added_cond_kwargs: TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by tin2tin** [huggingface/diffusers#4649] opened 2023-08-17 08:30 UTC
### Describe the bug

```
if "text_embeds" not in added_cond_kwargs:
TypeError: argument of type 'NoneType' is not iterable
```
I think I'm getting this error if I feed an image or a video which differs in resolution with the resolution a model was trained on, but I'm not sure exactly what is causing it. Maybe this description and solution might be a faster way to locate that bug: https://stackoverflow.com/questions/76707159/diffusers-sdxl-typeerror-argument-of-type-nonetype-is-not-iterable

### Reproduction

There is code linked here for reproduction: 
https://stackoverflow.com/questions/76707159/diffusers-sdxl-typeerror-argument-of-type-nonetype-is-not-iterable

### Logs

```shell
My log: 
Traceback (most recent call last):
  File "C:\Users\45239\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\Generative_AI-main\__init__.py", line 1224, in execute
    video_frames = upscale(
  File "C:\Users\45239\AppData\Roaming\Python\Python310\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\45239\AppData\Roaming\Python\Python310\site-packages\diffusers\pipelines\text_to_video_synthesis\pipeline_text_to_video_synth_img2img.py", line 670, in __call__
    noise_pred = self.unet(
  File "C:\Users\45239\AppData\Roaming\Python\Python310\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\45239\AppData\Roaming\Python\Python310\site-packages\accelerate\hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "C:\Users\45239\AppData\Roaming\Python\Python310\site-packages\diffusers\models\unet_2d_condition.py", line 840, in forward
    if "text_embeds" not in added_cond_kwargs:
TypeError: argument of type 'NoneType' is not iterable
Error: Python: Traceback (most recent call last):
  File "C:\Users\45239\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\Generative_AI-main\__init__.py", line 1224, in execute
    video_frames = upscale(
  File "C:\Users\45239\AppData\Roaming\Python\Python310\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\45239\AppData\Roaming\Python\Python310\site-packages\diffusers\pipelines\text_to_video_synthesis\pipeline_text_to_video_synth_img2img.py", line 670, in __call__
    noise_pred = self.unet(
  File "C:\Users\45239\AppData\Roaming\Python\Python310\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\45239\AppData\Roaming\Python\Python310\site-packages\accelerate\hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "C:\Users\45239\AppData\Roaming\Python\Python310\site-packages\diffusers\models\uneTraceback (most recent call last):
  File "C:\Users\45239\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\Generative_AI-main\__init__.py", line 1962, in execute
    sequencer.generate_movie()
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\45239\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\Generative_AI-main\__init__.py", line 1224, in execute
    video_frames = upscale(
  File "C:\Users\45239\AppData\Roaming\Python\Python310\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\45239\AppData\Roaming\Python\Python310\site-packages\diffusers\pipelines\text_to_video_synthesis\pipeline_text_to_video_synth_img2img.py", line 670, in __call__
    noise_pred = self.unet(
  File "C:\Users\45239\AppData\Roaming\Python\Python310\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\45239\AppData\Roaming\Python\Python310\site-packages\accelerate\hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "C:\Users\45239\AppData\Roaming\Python\Python310\site-packages\diffusers\models\unet_2d_condition.py", line 840, in forward
    if "text_embeds" not in added_cond_kwargs:
TypeError: argument of type 'NoneType' is not iterable
Location: C:\Program Files\Blender Foundation\Blender 3.5\3.5\scripts\modules\bpy\ops.py:113

Error: Python: Traceback (most recent call last):
  File "C:\Users\45239\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\Generative_AI-main\__init__.py", line 1962, in execute
    sequencer.generate_movie()
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\45239\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\Generative_AI-main\__init__.py", line 1224, in execute
    video_frames = upscale(
  File "C:\Users\45239\AppData\Roaming\Python\Python310\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\45239\AppData\Roaming\Python\Python310\site-packages\diffusers\pipelines\text_to_video_synthesis\pipeline_text_to_video_synth_img2img.py", line 670, in __call__
    noise_pred = self.unet(
  File "C:\Users\45239\AppData\Roaming\Python\Python310\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\45239\AppData\Roaming\Python\Python310\site-packages\accelerate\hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "C:\Users\45239\AppData\Roaming\Python\Python310\site-packages\diffusers\models\unet_2d_condition.py", line 840, in forward
    if "text_embeds" not in added_cond_kwargs:
TypeError: argument of type 'NoneType' is not iterable
Location: C:\Program Files\Blender Foundation\Blender 3.5\3.5\scripts\modules\bpy\ops.py:113
```

### System Info

Win 11
Diffusers 19.3

**Comment by seven-dev** [comment] 2023-08-17 17:41
I'm having the same issue

**Comment by sayakpaul** [comment] 2023-08-18 04:27
Please post a reproducible code snippet.

**Comment by tin2tin** [comment] 2023-08-18 04:55
@sayakpaul At the link, someone with the same error has posted code to reproduce it: https://hatebin.com/tqppqfsehk
And there is also a reply suggesting what might be causing the error, and how to fix it: https://stackoverflow.com/questions/76707159/diffusers-sdxl-typeerror-argument-of-type-nonetype-is-not-iterable

**Comment by sayakpaul** [comment] 2023-08-18 05:21
The code snippet seems to have irrelevant parts. Could we please have something more minimal? It helps us to reproduce the error very quickly. It could very well be because of the use of chaining incompatible components together.

**Comment by tin2tin** [comment] 2023-08-18 06:32
Oh, I'm afraid that will be too much work for me. It is not my code snippet. 

This sounds like a possible solution? 
![image](https://github.com/huggingface/diffusers/assets/1322593/75098d02-a112-4644-bcb1-5a1308580ac3)

**Comment by sayakpaul** [comment] 2023-08-18 06:41
Without a minimally reproducible code, I am afraid we cannot do much here. So, I am going to close the issue but feel free to reopen if you get around to a minimally reproducible snippet.

**Closed by sayakpaul** 2023-08-18 06:41 UTC
Labels: bug

**Comment by seven-dev** [comment] 2023-08-19 00:03
Hey @sayakpaul, this is the code and below is the error:

```python
import transformers
print(transformers.__version__)
from diffusers import ControlNetModel, StableDiffusionControlNetPipeline, AutoencoderKL
from diffusers.utils import load_image
from PIL import Image
import torch
import numpy as np
import cv2

prompt = "aerial view, a futuristic research complex in a bright foggy jungle, hard lighting"
negative_prompt = 'low quality, bad quality, sketches'

image = load_image("https://huggingface.co/datasets/hf-internal-testing/diffusers-images/resolve/main/sd_controlnet/hf-logo.png")

controlnet_conditioning_scale = 0.5  # recommended for good generalization

controlnet = ControlNetModel.from_pretrained(
    "diffusers/controlnet-canny-sdxl-1.0",
    torch_dtype=torch.float16
)
vae = AutoencoderKL.from_pretrained("madebyollin/sdxl-vae-fp16-fix", torch_dtype=torch.float16)
pipe = StableDiffusionControlNetPipeline.from_pretrained(
    "stabilityai/stable-diffusion-xl-base-1.0",
    controlnet=controlnet,
    vae=vae,
    torch_dtype=torch.float16,
)
pipe.enable_model_cpu_offload()

image = np.array(image)
image = cv2.Canny(image, 100, 200)
image = image[:, :, None]
image = np.concatenate([image, image, image], axis=2)
image = Image.fromarray(image)
```

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[2], line 27
     24 image = np.concatenate([image, image, image], axis=2)
     25 image = Image.fromarray(image)
---> 27 images = pipe(
     28     prompt, negative_prompt=negative_prompt, image=image, controlnet_conditioning_scale=controlnet_conditioning_scale,
     29     ).images
     31 images[0].save(f"hug_lab.png")

File /usr/local/lib/python3.8/dist-packages/torch/utils/_contextlib.py:115, in context_decorator.<locals>.decorate_context(*args, **kwargs)
    112 @functools.wraps(func)
    113 def decorate_context(*args, **kwargs):
    114     with ctx_factory():
--> 115         return func(*args, **kwargs)

File /usr/local/lib/python3.8/dist-packages/diffusers/pipelines/controlnet/pipeline_controlnet.py:955, in StableDiffusionControlNetPipeline.__call__(self, prompt, image, height, width, num_inference_steps, guidance_scale, negative_prompt, num_images_per_prompt, eta, generator, latents, prompt_embeds, negative_prompt_embeds, output_type, return_dict, callback, callback_steps, cross_attention_kwargs, controlnet_conditioning_scale, guess_mode, control_guidance_start, control_guidance_end)
    952         controlnet_cond_scale = controlnet_cond_scale[0]
    953     cond_scale = controlnet_cond_scale * controlnet_keep[i]
--> 955 down_block_res_samples, mid_block_res_sample = self.controlnet(
    956     control_model_input,
    957     t,
    958     encoder_hidden_states=controlnet_prompt_embeds,
    959     controlnet_cond=image,
    960     conditioning_scale=cond_scale,
    961     guess_mode=guess_mode,
    962     return_dict=False,
    963 )
    965 if guess_mode and do_classifier_free_guidance:
    966     # Infered ControlNet only for the conditional batch.
    967     # To apply the output of ControlNet to both the unconditional and conditional batches,
    968     # add 0 to the unconditional batch to keep it unchanged.
    969     down_block_res_samples = [torch.cat([torch.zeros_like(d), d]) for d in down_block_res_samples]

File /usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py:1501, in Module._call_impl(self, *args, **kwargs)
   1496 # If we don't have any hooks, we want to skip the rest of the logic in
   1497 # this function, and just call forward.
   1498 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1499         or _global_backward_pre_hooks or _global_backward_hooks
   1500         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1501     return forward_call(*args, **kwargs)
   1502 # Do not call functions when jit is used
   1503 full_backward_hooks, non_full_backward_hooks = [], []

File /usr/local/lib/python3.8/dist-packages/accelerate/hooks.py:165, in add_hook_to_module.<locals>.new_forward(*args, **kwargs)
    163         output = old_forward(*args, **kwargs)
    164 else:
--> 165     output = old_forward(*args, **kwargs)
    166 return module._hf_hook.post_forward(module, output)

File /usr/local/lib/python3.8/dist-packages/diffusers/models/controlnet.py:731, in ControlNetModel.forward(self, sample, timestep, encoder_hidden_states, controlnet_cond, conditioning_scale, class_labels, timestep_cond, attention_mask, added_cond_kwargs, cross_attention_kwargs, guess_mode, return_dict)
    728     aug_emb = self.add_embedding(encoder_hidden_states)
    730 elif self.config.addition_embed_type == "text_time":
--> 731     if "text_embeds" not in added_cond_kwargs:
    732         raise ValueError(
    733             f"{self.__class__} has the config param `addition_embed_type` set to 'text_time' which requires the keyword argument `text_embeds` to be passed in `added_cond_kwargs`"
    734         )
    735     text_embeds = added_cond_kwargs.get("text_embeds")

TypeError: argument of type 'NoneType' is not iterable
```

**Comment by sayakpaul** [comment] 2023-08-19 00:49
You are supposed to be using `StableDiffusionXLControlNetPipeline`.

**Comment by seven-dev** [comment] 2023-08-19 10:39
Alright, thank you. Do you know how much VRAM this XL model needs? I think I don't have enough (about 6GB).
Anyway, at least stable diffusion 2.1 is working for me, so I would consider this solved, thank you very much.

**Comment by rajbala** [comment] 2023-08-23 20:08
I am having this same problem outside of using ControlNet so I am not using `StableDiffusionXLControlNetPipeline`.  I am using `DiffusionPipeline`.  

Any suggestions?

**Comment by sayakpaul** [comment] 2023-08-24 01:49
You should be using `StableDiffusionXLControlNetPipeline`.

**Comment by earonesty** [comment] 2023-11-09 20:22
im using just regular "StableDiffusionPipeline" and it has this error

**Comment by DarkAlchy** [comment] 2024-01-13 20:30
> > im using just regular "StableDiffusionPipeline" and it has this error
> > i met the same error, and i solved it by using `StableDiffusionXLPipeline` instead of `StableDiffusionPipeline`.

I am using StableDiffusionXLPipeline to be met with this error.  pipe = StableDiffusionXLPipeline.from_single_file(checkpoint_path,torch_dtype=weight_dtype,cache_dir=DIFFUSERS_CACHE_DIR)

Traceback (most recent call last):
  File "F:\esd\test11.py", line 541, in <module>
    prompt_2_img()
  File "F:\esd\test11.py", line 462, in prompt_2_img
    denoised_latents = diffusion(unet, scheduler2, latents2, concat_embeddings(uncon_denoised_emb, targ_emb, batch_size), 7, infer_steps, start_timesteps)
  File "F:\esd\test11.py", line 189, in diffusion
    noise_pred = predict_noise(unet, scheduler, t, current_latents, token_embeddings, guidance_scale)
  File "F:\esd\test11.py", line 180, in predict_noise
    noise_pred = unet(latent_model_input, timestep, encoder_hidden_states=token_embeddings)["sample"]
  File "F:\esd\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "F:\esd\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "F:\esd\venv\lib\site-packages\diffusers\models\unet_2d_condition.py", line 1004, in forward
    if "text_embeds" not in added_cond_kwargs:
TypeError: argument of type 'NoneType' is not iterable

**Comment by CVerSMH** [comment] 2024-06-02 08:39
> 在链接中，具有相同错误的人发布了代码以重现它： https://hatebin.com/tqppqfsehk 还有一个回复，建议可能导致错误的原因，以及如何修复它： https://stackoverflow.com/questions/76707159/diffusers-sdxl-typeerror-argument-of-type-nonetype-is-not-iterable

This method is "Interme Antiem, there is Shorebe, Aburtowalk, Alandesis, Biexplispa, Sinsinaded_Kant_Kvoggs={} Totnut, Finktien." It didn't work

**Comment by CVerSMH** [comment] 2024-06-02 08:40
> 在链接中，具有相同错误的人发布了代码以重现它： https://hatebin.com/tqppqfsehk 还有一个回复，建议可能导致错误的原因，以及如何修复它： https://stackoverflow.com/questions/76707159/diffusers-sdxl-typeerror-argument-of-type-nonetype-is-not-iterable

This method is "Interme Antiem, there is Shorebe, Aburtowalk, Alandesis, Biexplispa, Sinsinaded_Kant_Kvoggs={} Totnut, Finktien." It didn't work

**Comment by CVerSMH** [comment] 2024-06-02 08:40
> 我有同样的问题

Hello, how did you solve this problem?

**Comment by jloveric** [comment] 2024-08-16 20:58
I appear to have solved this with the following code by adding addition_embed_type=None here.
```
controlnet = ControlNetModel.from_pretrained(
                "diffusers/controlnet-depth-sdxl-1.0",
                variant="fp16",
                torch_dtype=torch.float16,
                addition_embed_type=None
            ).to(self.device)
```
