### ISSUE TITLE
CompVis/stable-diffusion-v1-4 is missing fp16 files

### ISSUE THREAD

**Issue by vilobhmm** [huggingface/diffusers#2419] opened 2023-02-19 10:31 UTC
*Problem*

You are loading the variant fp16 from CompVis/stable-diffusion-v1-4 via `revision='fp16'`. This behavior is deprecated and will be removed in diffusers v1. One should use `variant='fp16'` instead. However, it appears that CompVis/stable-diffusion-v1-4 currently does not have the required variant filenames in the 'main' branch. 

*Action*

Taking appropriate action depending on the signal

The Diffusers team and community would be very grateful if you could open an issue: https://github.com/huggingface/diffusers/issues/new with the title 'CompVis/stable-diffusion-v1-4 is missing fp16 files' so that the correct variant file can be added.
  warnings.warn(

*Code snippet to reproduce problem*

model_id = "CompVis/stable-diffusion-v1-4"
device = "cuda"
pipe = StableDiffusionPipeline.from_pretrained(model_id, 
                                               #use_auth_token=True, 
                                               use_auth_token="XXX", 
                                               revision="fp16", 
                                               torch_dtype=torch.float16)
pipe = pipe.to(device)

**Comment by pcuenca** [comment] 2023-02-20 07:43
Hi @vilobhmm! Thanks a lot for reaching out! However this was a bug in the deprecation message that was fixed in #2426 (the message was designed to become active in a future release, not just now). Sorry for the confusion :)

**Closed by pcuenca** 2023-02-20 07:43 UTC

**Comment by patrickvonplaten** [comment] 2023-02-20 07:50
Also duplicate of https://github.com/huggingface/diffusers/pull/2305
